Config = Config or {}

Config.MinZOffset = 30

Config.RamsNeeded = 2

Config.Houses = {}
Config.HouseGarages = {}

Config.MinAmounts = {
    ["1"] = 25000,
    ["2"] = 40000,
    ["3"] = 55000,
    ["4"] = 80000,
	["5"] = 11000,
	["6"] = 15000,
	["7"] = 185000,
}

Config.Locations = {
	-- Everyone
	['enter'] = { ['x'] = -116.9713, ['y'] = -606.1077, ['z'] = 36.280715 },
	['exit'] = { ['x'] = -141.7568, ['y'] = -617.6605, ['z'] = 168.82031 },

	-- Whitelist
	['stash'] = { ['x'] = -129.9314, ['y'] = -633.6356, ['z'] = 168.82031 },
	['shop'] = { ['x'] = -133.5121, ['y'] = -645.1829, ['z'] = 168.82031 },
	['boss'] = { ['x'] = -125.5005, ['y'] = -640.8859, ['z'] = 168.82031 },
}

Config.Shop = {
    label = "Real Estate Items",
    slots = 1,
    items = {
		[1] = {
            name = "empy_contract",
            price = 0,
            amount = 1,
            type = "item",
            slot = 1,
        },
	}
}

Config.Furniture = {
	["sofas"] = {
		label = "Sofas",
		items = {
			[1] = { ["object"] = "miss_rub_couch_01", ["price"] = 300, ["label"] = "Old Sofa" },
			[2] = { ["object"] = "prop_fib_3b_bench", ["price"] = 700, ["label"] = "Three-seater bench" },
			[3] = { ["object"] = "prop_ld_farm_chair01", ["price"] = 250, ["label"] = "Old chair" },
			[4] = { ["object"] = "prop_ld_farm_couch01", ["price"] = 300, ["label"] = "Old three-seater sofa" },
			[5] = { ["object"] = "prop_ld_farm_couch02", ["price"] = 300, ["label"] = "Old striped sofa" },
			[6] = { ["object"] = "v_res_d_armchair", ["price"] = 300, ["label"] = "Old 1 Seat Couch Yellow" },
			[7] = { ["object"] = "v_res_fh_sofa", ["price"] = 3700, ["label"] = "Corner sofa" },
			[8] = { ["object"] = "v_res_mp_sofa", ["price"] = 3700, ["label"] = "Corner sofa 2" },
			[9] = { ["object"] = "v_res_d_sofa", ["price"] = 700, ["label"] = "Sofa 1" },
			[10] = { ["object"] = "v_res_j_sofa", ["price"] = 700, ["label"] = "Sofa 2" },
			[11] = { ["object"] = "v_res_mp_stripchair", ["price"] = 700, ["label"] = "Sofa 3" },
			[12] = { ["object"] = "v_res_m_h_sofa_sml", ["price"] = 700, ["label"] = "Sofa 4" },
			[13] = { ["object"] = "v_res_r_sofa", ["price"] = 700, ["label"] = "Sofa 5" },
			[14] = { ["object"] = "v_res_tre_sofa", ["price"] = 700, ["label"] = "Sofa 6" },
			[15] = { ["object"] = "v_res_tre_sofa_mess_a", ["price"] = 700, ["label"] = "Sofa 7" },
			[16] = { ["object"] = "v_res_tre_sofa_mess_b", ["price"] = 700, ["label"] = "Sofa 8" },
			[17] = { ["object"] = "v_res_tre_sofa_mess_c", ["price"] = 700, ["label"] = "Sofa 9" },
			[18] = { ["object"] = "v_res_tt_sofa", ["price"] = 700, ["label"] = "Sofa 10" },
			[19] = { ["object"] = "prop_rub_couch02", ["price"] = 700, ["label"] = "Sofa 11" },
			[20] = { ["object"] = "v_ilev_m_sofa", ["price"] = 2000, ["label"] = "White Sofa" },
			[21] = { ["object"] = "v_med_p_sofa", ["price"] = 1000, ["label"] = "Leather Sofa Brown" },
			[22] = { ["object"] = "v_club_officesofa", ["price"] = 500, ["label"] = "Office Sofa red" },
			[23] = { ["object"] = "bkr_prop_clubhouse_sofa_01a", ["price"] = 1000, ["label"] = "Black Sofa" },
			[24] = { ["object"] = "apa_mp_h_stn_sofacorn_01", ["price"] = 5000, ["label"] = "Corner Sofa 3" },
			[25] = { ["object"] = "prop_couch_lg_02", ["price"] = 1000, ["label"] = "Bench Wood" },
			[26] = { ["object"] = "apa_mp_h_stn_sofacorn_10", ["price"] = 5000, ["label"] = "Corner Sofa 4" },
			[27] = { ["object"] = "apa_mp_h_yacht_sofa_02", ["price"] = 1000, ["label"] = "Brown Sofa" },
			[28] = { ["object"] = "apa_mp_h_yacht_sofa_01", ["price"] = 5000, ["label"] = "White Long Sofa" },
			[29] = { ["object"] = "prop_couch_01", ["price"] = 1000, ["label"] = "Sofa Cushions" },
			[30] = { ["object"] = "prop_couch_03", ["price"] = 1000, ["label"] = "Yellow Sofa" },
			[31] = { ["object"] = "prop_couch_04", ["price"] = 1000, ["label"] = "Leather Sofa Cushions" },
			[32] = { ["object"] = "prop_couch_lg_05", ["price"] = 500, ["label"] = "Sofa Corduroy" },
			[33] = { ["object"] = "prop_couch_lg_06", ["price"] = 1000, ["label"] = "Leather Brown Sofa 2" },
			[34] = { ["object"] = "prop_couch_lg_07", ["price"] = 1000, ["label"] = "Sofa Cushions 2" },
			[35] = { ["object"] = "prop_couch_lg_08", ["price"] = 1000, ["label"] = "Leather Brown Sofa 3" },
			[36] = { ["object"] = "prop_couch_sm1_07", ["price"] = 500, ["label"] = "Leather Sofa Corner" },
			[37] = { ["object"] = "prop_couch_sm2_07", ["price"] = 500, ["label"] = "Leather Sofa Straight" },
			[38] = { ["object"] = "prop_couch_sm_06", ["price"] = 500, ["label"] = "Leather Sofa Small" },
			[39] = { ["object"] = "apa_mp_h_stn_sofa2seat_02", ["price"] = 1000, ["label"] = "Seat" },
			[40] = { ["object"] = "apa_mp_h_stn_sofacorn_05", ["price"] = 5000, ["label"] = "Corner Sofa 5" },
			[41] = { ["object"] = "apa_mp_h_stn_sofacorn_06", ["price"] = 5000, ["label"] = "Corner Sofa 6" },
			[42] = { ["object"] = "apa_mp_h_stn_sofacorn_07", ["price"] = 5000, ["label"] = "Corner Sofa 7" },
			[43] = { ["object"] = "apa_mp_h_stn_sofacorn_08", ["price"] = 5000, ["label"] = "Corner Sofa 8" },
			[44] = { ["object"] = "apa_mp_h_stn_sofacorn_09", ["price"] = 5000, ["label"] = "Corner Sofa 9" },
			[45] = { ["object"] = "ex_mp_h_off_sofa_003", ["price"] = 1000, ["label"] = "Fabric Blue Sofa" },
			[46] = { ["object"] = "ex_mp_h_off_sofa_01", ["price"] = 1000, ["label"] = "White Leather Sofa" },
			[47] = { ["object"] = "ex_mp_h_off_sofa_02", ["price"] = 1000, ["label"] = "Black Leather Sofa" },
			[48] = { ["object"] = "hei_heist_stn_sofa2seat_03", ["price"] = 1000, ["label"] = "Modern Sofa" },
			[49] = { ["object"] = "hei_heist_stn_sofa2seat_06", ["price"] = 1000, ["label"] = "Brown Sofa" },
			[50] = { ["object"] = "hei_heist_stn_sofa3seat_01", ["price"] = 1000, ["label"] = "Chaise Longue" },
			[51] = { ["object"] = "hei_heist_stn_sofa3seat_02", ["price"] = 1000, ["label"] = "Modern Sofa 2" },
			[52] = { ["object"] = "hei_heist_stn_sofa3seat_06", ["price"] = 1000, ["label"] = "Modern Sofa 3" },
			[53] = { ["object"] = "imp_prop_impexp_sofabed_01a", ["price"] = 1000, ["label"] = "Sofa Bed" },
			[54] = { ["object"] = "prop_t_sofa_02", ["price"] = 1000, ["label"] = "Sofa Bed 2" }
		},
	},
	["chairs"] = {
		label = "Chairs",
		items = {
			[1] = { ["object"] = "v_res_d_highchair", ["price"] = 700, ["label"] = "High Chair" },
			[2] = { ["object"] = "apa_mp_h_stn_chairstrip_03", ["price"] = 500, ["label"] = "Sitting Chair 4" },
			[3] = { ["object"] = "v_res_fa_chair01", ["price"] = 700, ["label"] = "Chair" },
			[4] = { ["object"] = "v_res_fa_chair02", ["price"] = 700, ["label"] = "Chair 2" },
			[5] = { ["object"] = "v_res_fh_barcchair", ["price"] = 700, ["label"] = "High Chair 2" },
			[6] = { ["object"] = "v_res_fh_dineeamesa", ["price"] = 700, ["label"] = "Kitchen Chair 1" },
			[7] = { ["object"] = "v_res_fh_dineeamesb", ["price"] = 700, ["label"] = "Kitchen Chair 2" },
			[8] = { ["object"] = "v_res_fh_dineeamesc", ["price"] = 700, ["label"] = "Kitchen Chair 3" },
			[9] = { ["object"] = "v_res_fh_easychair", ["price"] = 700, ["label"] = "Chair 3" },
			[10] = { ["object"] = "v_res_fh_kitnstool", ["price"] = 700, ["label"] = "Chair 4" },
			[11] = { ["object"] = "v_res_fh_singleseat", ["price"] = 700, ["label"] = "High Chair 3" },
			[12] = { ["object"] = "v_res_jarmchair", ["price"] = 700, ["label"] = "Arm Chair" },
			[13] = { ["object"] = "v_res_j_dinechair", ["price"] = 700, ["label"] = "Kitchen Chair 4" },
			[14] = { ["object"] = "v_res_j_stool", ["price"] = 700, ["label"] = "Chair 5" },
			[15] = { ["object"] = "v_res_mbchair", ["price"] = 700, ["label"] = "MB Chair" },
			[16] = { ["object"] = "v_res_m_armchair", ["price"] = 700, ["label"] = "Arm Chair 2" },
			[17] = { ["object"] = "v_res_m_dinechair", ["price"] = 700, ["label"] = "Kitchen Chair 5" },
			[18] = { ["object"] = "v_res_study_chair", ["price"] = 700, ["label"] = "Study Chair" },
			[19] = { ["object"] = "v_res_trev_framechair", ["price"] = 700, ["label"] = "Chair Frame" },
			[20] = { ["object"] = "v_res_tre_chair", ["price"] = 700, ["label"] = "Chair 5" },
			[21] = { ["object"] = "v_res_tre_officechair", ["price"] = 700, ["label"] = "Office Chair" },
			[22] = { ["object"] = "v_res_tre_stool", ["price"] = 700, ["label"] = "Chair 6" },
			[23] = { ["object"] = "v_res_tre_stool_leather", ["price"] = 700, ["label"] = "School Chair" },
			[24] = { ["object"] = "v_res_tre_stool_scuz", ["price"] = 700, ["label"] = "Chair Scuz" },
			[25] = { ["object"] = "v_med_p_deskchair", ["price"] = 700, ["label"] = "Office Chair" },
			[26] = { ["object"] = "v_med_p_easychair", ["price"] = 700, ["label"] = "Easy Chair" },
			[27] = { ["object"] = "v_med_whickerchair1", ["price"] = 700, ["label"] = "Whicker Chair" },
			[28] = { ["object"] = "prop_direct_chair_01", ["price"] = 700, ["label"] = "Direct Chair" },
			[29] = { ["object"] = "prop_direct_chair_02", ["price"] = 700, ["label"] = "Direct Chair 2" },
			[30] = { ["object"] = "prop_yacht_lounger", ["price"] = 700, ["label"] = "Yacht Chair 1" },
			[31] = { ["object"] = "prop_yacht_seat_01", ["price"] = 700, ["label"] = "Yacht Chair 2" },
			[32] = { ["object"] = "prop_yacht_seat_02", ["price"] = 700, ["label"] = "Yacht Chair 3" },
			[33] = { ["object"] = "prop_yacht_seat_03", ["price"] = 700, ["label"] = "Yacht Chair 4" },
			[34] = { ["object"] = "v_ret_chair_white", ["price"] = 100, ["label"] = "White Chair" },
			[35] = { ["object"] = "v_ret_chair", ["price"] = 100, ["label"] = "Chair 7" },
			[36] = { ["object"] = "v_ret_ta_stool", ["price"] = 100, ["label"] = "TA Chair" },
			[37] = { ["object"] = "prop_cs_office_chair", ["price"] = 100, ["label"] = "Office Chair 2" },
			[38] = { ["object"] = "apa_mp_h_yacht_armchair_01", ["price"] = 1000, ["label"] = "White Armchair" },
			[39] = { ["object"] = "v_club_barchair", ["price"] = 300, ["label"] = "Chair 8" },
			[40] = { ["object"] = "prop_off_chair_04", ["price"] = 300, ["label"] = "Office Chair 2" },
			[41] = { ["object"] = "v_club_stagechair", ["price"] = 500, ["label"] = "Pink Arm" },
			[42] = { ["object"] = "v_club_officechair", ["price"] = 500, ["label"] = "Office Chair 3" },
			[43] = { ["object"] = "prop_armchair_01", ["price"] = 500, ["label"] = "Sitting Chair" },
			[44] = { ["object"] = "prop_bar_stool_01", ["price"] = 300, ["label"] = "Barstool" },
			[45] = { ["object"] = "apa_mp_h_yacht_stool_01", ["price"] = 300, ["label"] = "White Pouffe" },
			[46] = { ["object"] = "apa_mp_h_stn_chairarm_12", ["price"] = 500, ["label"] = "Sitting Chair 3" },
			[47] = { ["object"] = "apa_mp_h_stn_chairstool_12", ["price"] = 300, ["label"] = "Footrest" },
			[48] = { ["object"] = "prop_chair_03", ["price"] = 100, ["label"] = "Wooden Chair" },
			[49] = { ["object"] = "prop_couch_sm_05", ["price"] = 500, ["label"] = "Corduroy Armchair" },
			[50] = { ["object"] = "prop_couch_sm_07", ["price"] = 300, ["label"] = "White Armchair 2" },
			[51] = { ["object"] = "prop_couch_sm_02", ["price"] = 300, ["label"] = "Orange Armchair" },
			[52] = { ["object"] = "apa_mp_h_stn_sofa_daybed_01", ["price"] = 500, ["label"] = "Longue Chair" },
			[53] = { ["object"] = "apa_mp_h_stn_sofa_daybed_02", ["price"] = 500, ["label"] = "Longue Chair 2" },
			[54] = { ["object"] = "apa_mp_h_din_chair_04", ["price"] = 500, ["label"] = "Modern Chair" },
			[55] = { ["object"] = "apa_mp_h_din_chair_08", ["price"] = 500, ["label"] = "Modern Chair 2" },
			[56] = { ["object"] = "apa_mp_h_din_chair_09", ["price"] = 500, ["label"] = "Modern Chair 3" },
			[57] = { ["object"] = "apa_mp_h_din_chair_12", ["price"] = 500, ["label"] = "Modern Chair 4" },
			[58] = { ["object"] = "apa_mp_h_din_stool_04", ["price"] = 500, ["label"] = "Modern Chair 5" },
			[59] = { ["object"] = "apa_mp_h_stn_chairarm_01", ["price"] = 500, ["label"] = "Modern Chair 6" },
			[60] = { ["object"] = "apa_mp_h_stn_chairarm_02", ["price"] = 500, ["label"] = "Modern Chair 7" },
			[61] = { ["object"] = "apa_mp_h_stn_chairarm_03", ["price"] = 500, ["label"] = "Modern Chair 8" },
			[62] = { ["object"] = "apa_mp_h_stn_chairarm_09", ["price"] = 500, ["label"] = "Modern Chair 9" },
			[63] = { ["object"] = "apa_mp_h_stn_chairarm_11", ["price"] = 500, ["label"] = "Modern Chair 10" },
			[64] = { ["object"] = "apa_mp_h_stn_chairarm_13", ["price"] = 500, ["label"] = "Modern Chair 11" },
			[65] = { ["object"] = "apa_mp_h_stn_chairarm_24", ["price"] = 500, ["label"] = "Modern Chair 12" },
			[66] = { ["object"] = "apa_mp_h_stn_chairarm_25", ["price"] = 500, ["label"] = "Modern Chair 13" },
			[67] = { ["object"] = "apa_mp_h_stn_chairarm_26", ["price"] = 500, ["label"] = "Modern Chair 14" },
			[68] = { ["object"] = "apa_mp_h_stn_chairstrip_04", ["price"] = 500, ["label"] = "Modern Chair 15" },
			[69] = { ["object"] = "apa_mp_h_stn_chairstrip_05", ["price"] = 500, ["label"] = "Modern Chair 16" },
			[70] = { ["object"] = "apa_mp_h_stn_chairstrip_08", ["price"] = 500, ["label"] = "Modern Chair 17" },
			[71] = { ["object"] = "apa_mp_h_stn_foot_stool_01", ["price"] = 500, ["label"] = "Pouffe" },
			[72] = { ["object"] = "apa_mp_h_stn_foot_stool_02", ["price"] = 500, ["label"] = "Pouffe 2" },
			[73] = { ["object"] = "apa_mp_h_yacht_barstool_01", ["price"] = 500, ["label"] = "Barstool 2" },
			[74] = { ["object"] = "ba_prop_int_glam_stool", ["price"] = 500, ["label"] = "Barstool 3" },
			[75] = { ["object"] = "ba_prop_int_glam_stool", ["price"] = 500, ["label"] = "Barstool 4" },
			[76] = { ["object"] = "ba_prop_battle_club_chair_01", ["price"] = 500, ["label"] = "Office Chair" },
			[77] = { ["object"] = "ba_prop_battle_club_chair_02", ["price"] = 500, ["label"] = "Office Chair 2" },
			[78] = { ["object"] = "ba_prop_battle_club_chair_03", ["price"] = 500, ["label"] = "Office Chair 3" },
			[79] = { ["object"] = "ba_prop_battle_control_seat", ["price"] = 500, ["label"] = "Gaming Chair" }
		},
	},
	["beds"] = {
		label = "Beds",
		items = {
			[1] = { ["object"] = "v_res_d_bed", ["price"] = 700, ["label"] = "Bed 1" },	
			[2] = { ["object"] = "v_res_lestersbed", ["price"] = 700, ["label"] = "Bed 2" },	
			[3] = { ["object"] = "v_res_mbbed", ["price"] = 700, ["label"] = "MB Bed" },	
			[4] = { ["object"] = "v_res_mdbed", ["price"] = 700, ["label"] = "MD Bed" },	
			[5] = { ["object"] = "v_res_msonbed", ["price"] = 700, ["label"] = "Bed 3" },	
			[6] = { ["object"] = "v_res_tre_bed1", ["price"] = 700, ["label"] = "Bed 4" },	
			[7] = { ["object"] = "v_res_tre_bed2", ["price"] = 700, ["label"] = "T Bed" },	
			[8] = { ["object"] = "v_res_tt_bed", ["price"] = 700, ["label"] = "TT Bed" },
			[9] = { ["object"] = "apa_mp_h_bed_with_table_02", ["price"] = 5000, ["label"] = "Fancy Bed" },
			[10] = { ["object"] = "apa_mp_h_bed_wide_05", ["price"] = 5000, ["label"] = "Red Bed" },
			[11] = { ["object"] = "apa_mp_h_bed_double_08", ["price"] = 3000, ["label"] = "Square Bed" },	
			[12] = { ["object"] = "apa_mp_h_bed_double_09", ["price"] = 3000, ["label"] = "Modern Bed" },	
			[13] = { ["object"] = "apa_mp_h_yacht_bed_01", ["price"] = 5000, ["label"] = "California King" },
			[14] = { ["object"] = "apa_mp_h_yacht_bed_02", ["price"] = 5000, ["label"] = "California King 2" },
			[15] = { ["object"] = "bkr_prop_biker_campbed_01", ["price"] = 100, ["label"] = "Campbed" },
			[16] = { ["object"] = "ex_prop_exec_bed_01", ["price"] = 700, ["label"] = "Small bed" },
			[17] = { ["object"] = "gr_prop_bunker_bed_01", ["price"] = 700, ["label"] = "Small bed 2" }
		},	
	},
	["general"] = {
		label = "General",
		items = {
			[1] = { ["object"] = "v_corp_facebeanbag", ["price"] = 100, ["label"] = "Bean Bag 1" },
			[2] = { ["object"] = "v_res_cherubvase", ["price"] = 2500, ["label"] = "White Vase" },
			[3] = { ["object"] = "v_res_d_paddedwall", ["price"] = 300, ["label"] = "Padded Wall" },
			[4] = { ["object"] = "v_res_d_ramskull", ["price"] = 300, ["label"] = "Item" },
			[5] = { ["object"] = "v_res_d_whips", ["price"] = 300, ["label"] = "Whips" },
			[6] = { ["object"] = "v_res_fashmag1", ["price"] = 300, ["label"] = "Mags" },
			[7] = { ["object"] = "v_res_fashmagopen", ["price"] = 300, ["label"] = "Mags Open" },
			[8] = { ["object"] = "v_res_fa_magtidy", ["price"] = 300, ["label"] = "Mag Tidy" },
			[9] = { ["object"] = "v_res_fa_yogamat002", ["price"] = 300, ["label"] = "Yoga Mat 1" },
			[10] = { ["object"] = "v_res_fa_yogamat1", ["price"] = 300, ["label"] = "Yoga Mat 2" },
			[11] = { ["object"] = "v_res_fh_aftershavebox", ["price"] = 300, ["label"] = "Aftershave" },
			[12] = { ["object"] = "v_res_fh_flowersa", ["price"] = 300, ["label"] = "Flowers" },
			[13] = { ["object"] = "v_res_fh_fruitbowl", ["price"] = 300, ["label"] = "Fruitbowl" },
			[14] = { ["object"] = "v_res_fh_laundrybasket", ["price"] = 300, ["label"] = "Laundry Basket" },
			[15] = { ["object"] = "v_res_fh_pouf", ["price"] = 300, ["label"] = "Pouf" },
			[16] = { ["object"] = "v_res_fh_sculptmod", ["price"] = 300, ["label"] = "Sculpture" },
			[17] = { ["object"] = "v_res_j_magrack", ["price"] = 300, ["label"] = "Mag Rack" },
			[18] = { ["object"] = "v_res_jewelbox", ["price"] = 300, ["label"] = "Jewel Box" },
			[19] = { ["object"] = "v_res_mbbin", ["price"] = 300, ["label"] = "Bin" },
			[20] = { ["object"] = "v_res_mbowlornate", ["price"] = 300, ["label"] = "Ornate Bowl" },
			[21] = { ["object"] = "v_res_mbronzvase", ["price"] = 300, ["label"] = "Bronze Vase" },
			[22] = { ["object"] = "v_res_mchalkbrd", ["price"] = 300, ["label"] = "Chalk Board" },
			[23] = { ["object"] = "v_res_mddresser", ["price"] = 300, ["label"] = "Dresser" },
			[24] = { ["object"] = "v_res_mplinth", ["price"] = 300, ["label"] = "Linth" },
			[25] = { ["object"] = "v_res_mp_ashtrayb", ["price"] = 300, ["label"] = "Ashtray" },
			[26] = { ["object"] = "v_res_m_candle", ["price"] = 300, ["label"] = "Candle" },
			[27] = { ["object"] = "v_res_m_candlelrg", ["price"] = 300, ["label"] = "Candle Large" },
			[28] = { ["object"] = "v_res_m_kscales", ["price"] = 300, ["label"] = "Scales" },
			[29] = { ["object"] = "v_res_tt_bedpillow", ["price"] = 300, ["label"] = "Bed Pillow" },
			[30] = { ["object"] = "v_med_cor_whiteboard", ["price"] = 300, ["label"] = "White Board" },
			[31] = { ["object"] = "prop_ashtray_01", ["price"] = 100, ["label"] = "Black Ashtray" },
			[32] = { ["object"] = "v_ret_fh_ashtray", ["price"] = 100, ["label"] = "Stone Ashtray" },
			[33] = { ["object"] = "v_24_wdr_mesh_rugs", ["price"] = 500, ["label"] = "Dress" },
			[34] = { ["object"] = "apa_mp_h_acc_rugwooll_04", ["price"] = 500, ["label"] = "Dress 2" },
			[35] = { ["object"] = "ex_mp_h_acc_rugwoolm_04", ["price"] = 500, ["label"] = "Dress 3" },
			[36] = { ["object"] = "apa_mp_h_acc_rugwoolm_03", ["price"] = 500, ["label"] = "Dress 4" },
			[37] = { ["object"] = "apa_mp_h_acc_rugwooll_03", ["price"] = 500, ["label"] = "Dress 5" },
			[38] = { ["object"] = "apa_mp_h_acc_rugwoolm_04", ["price"] = 500, ["label"] = "Dress 6" },
			[39] = { ["object"] = "v_club_rack", ["price"] = 500, ["label"] = "Clothing Rack" }	
		},
	},
	["general2"] = {
		label = "Props",
		items = {
			[1] = { ["object"] = "prop_a4_pile_01", ["price"] = 100, ["label"] = "A4 Pile" },
			[2] = { ["object"] = "prop_amb_40oz_03", ["price"] = 100, ["label"] = "40 Oz" },
			[3] = { ["object"] = "prop_amb_beer_bottle", ["price"] = 100, ["label"] = "Beer" },
			[4] = { ["object"] = "prop_aviators_01", ["price"] = 100, ["label"] = "Aviators" },
			[5] = { ["object"] = "prop_barry_table_detail", ["price"] = 100, ["label"] = "Detail" },
			[6] = { ["object"] = "prop_beer_box_01", ["price"] = 100, ["label"] = "Beers" },
			[7] = { ["object"] = "prop_binoc_01", ["price"] = 100, ["label"] = "Binoculars" },
			[8] = { ["object"] = "prop_blox_spray", ["price"] = 100, ["label"] = "Blox Spray" },
			[9] = { ["object"] = "prop_bongos_01", ["price"] = 100, ["label"] = "Bongos" },
			[10] = { ["object"] = "prop_bong_01", ["price"] = 100, ["label"] = "Bong" },
			[11] = { ["object"] = "prop_boombox_01", ["price"] = 100, ["label"] = "Boombox" },
			[12] = { ["object"] = "prop_bowl_crisps", ["price"] = 100, ["label"] = "Bowl Crisps" },
			[13] = { ["object"] = "prop_candy_pqs", ["price"] = 100, ["label"] = "Candy" },
			[14] = { ["object"] = "prop_carrier_bag_01", ["price"] = 100, ["label"] = "Carrier bag" },
			[15] = { ["object"] = "prop_ceramic_jug_01", ["price"] = 100, ["label"] = "Ceramic Jug" },
			[16] = { ["object"] = "prop_cigar_pack_01", ["price"] = 100, ["label"] = "Cigar Pack 1" },
			[17] = { ["object"] = "prop_cigar_pack_02", ["price"] = 100, ["label"] = "Cigar Pack 2" },
			[18] = { ["object"] = "prop_cs_beer_box", ["price"] = 100, ["label"] = "Beer Box 2" },
			[19] = { ["object"] = "prop_cs_binder_01", ["price"] = 100, ["label"] = "Binder" },
			[20] = { ["object"] = "prop_cs_bs_cup", ["price"] = 100, ["label"] = "Cup" },
			[21] = { ["object"] = "prop_cs_cashenvelope", ["price"] = 100, ["label"] = "Envelope" },
			[22] = { ["object"] = "prop_cs_champ_flute", ["price"] = 100, ["label"] = "Flute" },
			[23] = { ["object"] = "prop_cs_duffel_01", ["price"] = 100, ["label"] = "Duffel Bag" },
			[24] = { ["object"] = "prop_cs_dvd", ["price"] = 50, ["label"] = "DVD" },
			[25] = { ["object"] = "prop_cs_dvd_case", ["price"] = 50, ["label"] = "DVD Case" },
			[26] = { ["object"] = "prop_cs_film_reel_01", ["price"] = 100, ["label"] = "Film Reel" },
			[27] = { ["object"] = "prop_cs_ilev_blind_01", ["price"] = 100, ["label"] = "Blind" },
			[28] = { ["object"] = "p_ld_bs_bag_01", ["price"] = 100, ["label"] = "Bag" },
			[29] = { ["object"] = "prop_cs_ironing_board", ["price"] = 100, ["label"] = "Ironing Board" },
			[30] = { ["object"] = "prop_cs_katana_01", ["price"] = 100, ["label"] = "Katana" },
			[31] = { ["object"] = "prop_cs_kettle_01", ["price"] = 100, ["label"] = "Kettle" },
			[32] = { ["object"] = "prop_cs_lester_crate", ["price"] = 100, ["label"] = "Crate" },
			[33] = { ["object"] = "prop_cs_petrol_can", ["price"] = 100, ["label"] = "Petrol Can" },
			[34] = { ["object"] = "prop_cs_sack_01", ["price"] = 100, ["label"] = "Sack" },
			[35] = { ["object"] = "prop_cs_script_bottle_01", ["price"] = 100, ["label"] = "Script Bottle" },
			[36] = { ["object"] = "prop_cs_script_bottle", ["price"] = 100, ["label"] = "Script Bottle 2" },
			[37] = { ["object"] = "prop_cs_street_binbag_01", ["price"] = 100, ["label"] = "Bin Bag" },
			[38] = { ["object"] = "prop_cs_whiskey_bottle", ["price"] = 100, ["label"] = "Whiskey Bottle" },
			[39] = { ["object"] = "prop_sh_bong_01", ["price"] = 100, ["label"] = "Bong" },
			[40] = { ["object"] = "prop_peanut_bowl_01", ["price"] = 100, ["label"] = "Peanuts" },
			[41] = { ["object"] = "prop_tumbler_01", ["price"] = 100, ["label"] = "Tumbler" },
			[42] = { ["object"] = "prop_weed_bottle", ["price"] = 100, ["label"] = "Weed Bottle" },
			[43] = { ["object"] = "p_cs_lighter_01", ["price"] = 100, ["label"] = "Lighter" },
			[44] = { ["object"] = "p_cs_papers_01", ["price"] = 100, ["label"] = "Papers" },
			[45] = { ["object"] = "v_res_d_dildo_f", ["price"] = 100, ["label"] = "Black Dildo" },
			[46] = { ["object"] = "v_res_d_dildo_c", ["price"] = 100, ["label"] = "White Dildo" },
			[47] = { ["object"] = "v_res_d_dildo_a", ["price"] = 100, ["label"] = "Exciting Dildo" },
			[48] = { ["object"] = "prop_champ_cool", ["price"] = 100, ["label"] = "Champagne Cooler" },
			[49] = { ["object"] = "prop_champ_01b", ["price"] = 100, ["label"] = "Champagne Bottle" },
			[50] = { ["object"] = "prop_champ_flute", ["price"] = 100, ["label"] = "Champagne Glass" },
			[51] = { ["object"] = "ba_prop_club_champset", ["price"] = 300, ["label"] = "Champagne Set" },
			[52] = { ["object"] = "v_res_fa_candle01", ["price"] = 100, ["label"] = "Blue Candle" },
			[53] = { ["object"] = "v_res_fa_candle02", ["price"] = 100, ["label"] = "Red Candle" },
			[54] = { ["object"] = "v_res_fa_candle03", ["price"] = 100, ["label"] = "Green Candle" },
			[55] = { ["object"] = "v_res_fa_candle04", ["price"] = 100, ["label"] = "Small Candle" },
			[56] = { ["object"] = "v_med_bottles2", ["price"] = 100, ["label"] = "Chemicals" },
			[57] = { ["object"] = "v_res_desktidy", ["price"] = 100, ["label"] = "Office Supplies" },
			[58] = { ["object"] = "v_med_p_notebook", ["price"] = 100, ["label"] = "Notes" },
			[59] = { ["object"] = "bkr_prop_weed_dry_01a", ["price"] = 100, ["label"] = "Heap of Weed" },
			[60] = { ["object"] = "ba_prop_battle_trophy_battler", ["price"] = 100, ["label"] = "Fist Trophy" },
			[61] = { ["object"] = "ba_prop_battle_trophy_no1", ["price"] = 100, ["label"] = "Star Trophy" },
			[62] = { ["object"] = "prop_golf_bag_01c", ["price"] = 100, ["label"] = "Golf Bag" },
			[63] = { ["object"] = "hei_heist_kit_bin_01", ["price"] = 100, ["label"] = "Garbage Can" },
			[64] = { ["object"] = "prop_wooden_barrel", ["price"] = 100, ["label"] = "Wooden Barrel" }
		},
	},
	["general3"] = {
		label = "Random",
		items = {
			[1] = { ["object"] = "v_ret_csr_bin", ["price"] = 100, ["label"] = "CSR Bin" },
			[2] = { ["object"] = "v_ret_fh_wickbskt", ["price"] = 100, ["label"] = "Basket" },
			[3] = { ["object"] = "v_ret_gc_bag01", ["price"] = 100, ["label"] = "GC Bag 1" },
			[4] = { ["object"] = "v_ret_gc_bag02", ["price"] = 100, ["label"] = "GC Bag 2" },
			[5] = { ["object"] = "v_ret_gc_bin", ["price"] = 100, ["label"] = "GC Bin" },
			[6] = { ["object"] = "v_ret_gc_cashreg", ["price"] = 100, ["label"] = "Cash Register" },
			[7] = { ["object"] = "v_ret_gc_chair01", ["price"] = 100, ["label"] = "GC Chair 01" },
			[8] = { ["object"] = "v_ret_gc_chair02", ["price"] = 100, ["label"] = "GC Chair 02" },
			[9] = { ["object"] = "v_ret_gc_clock", ["price"] = 100, ["label"] = "Clock" },
			[10] = { ["object"] = "v_ret_hd_prod1_", ["price"] = 100, ["label"] = "Prod 1" },
			[11] = { ["object"] = "v_ret_hd_prod2_", ["price"] = 100, ["label"] = "Prod 2" },
			[12] = { ["object"] = "v_ret_hd_prod3_", ["price"] = 100, ["label"] = "Prod 3" },
			[13] = { ["object"] = "v_ret_hd_prod4_", ["price"] = 100, ["label"] = "Prod 4" },
			[14] = { ["object"] = "v_ret_hd_prod5_", ["price"] = 100, ["label"] = "Prod 5" },
			[15] = { ["object"] = "v_ret_hd_prod6_", ["price"] = 100, ["label"] = "Prod 6" },
			[16] = { ["object"] = "v_ret_hd_unit1_", ["price"] = 100, ["label"] = "HD Unit 1" },
			[17] = { ["object"] = "v_ret_hd_unit2_", ["price"] = 100, ["label"] = "HD Unit 2" },
			[18] = { ["object"] = "v_ret_ml_fridge02", ["price"] = 100, ["label"] = "Fridge" },
			[19] = { ["object"] = "v_ret_ps_bag_01", ["price"] = 100, ["label"] = "Bag 1" },
			[20] = { ["object"] = "v_ret_ps_bag_02", ["price"] = 100, ["label"] = "Bag 2" },
			[21] = { ["object"] = "v_ret_ta_book1", ["price"] = 100, ["label"] = "Book 1" },
			[22] = { ["object"] = "v_ret_ta_book2", ["price"] = 100, ["label"] = "Book 2" },
			[23] = { ["object"] = "v_ret_ta_book3", ["price"] = 100, ["label"] = "Book 3" },
			[24] = { ["object"] = "v_ret_ta_book4", ["price"] = 100, ["label"] = "Book 4" },
			[25] = { ["object"] = "v_ret_ta_camera", ["price"] = 100, ["label"] = "Cam" },
			[26] = { ["object"] = "v_ret_ta_firstaid", ["price"] = 100, ["label"] = "First Aid" },
			[27] = { ["object"] = "v_ret_ta_hero", ["price"] = 100, ["label"] = "Hero" },
			[28] = { ["object"] = "v_ret_ta_mag1", ["price"] = 100, ["label"] = "Mag 1" },
			[29] = { ["object"] = "v_ret_ta_mag2", ["price"] = 100, ["label"] = "Mag 2" },
			[30] = { ["object"] = "v_ret_ta_skull", ["price"] = 100, ["label"] = "Skull" },
			[31] = { ["object"] = "prop_acc_guitar_01", ["price"] = 100, ["label"] = "Guitar" },
			[32] = { ["object"] = "prop_amb_handbag_01", ["price"] = 100, ["label"] = "Handbag" },
			[33] = { ["object"] = "prop_attache_case_01", ["price"] = 100, ["label"] = "Case" },
			[34] = { ["object"] = "prop_big_bag_01", ["price"] = 100, ["label"] = "Big Bag" },
			[35] = { ["object"] = "prop_bonesaw", ["price"] = 100, ["label"] = "Bonesaw" },
			[36] = { ["object"] = "prop_cs_fertilizer", ["price"] = 100, ["label"] = "Fertilizer" },
			[37] = { ["object"] = "prop_cs_shopping_bag", ["price"] = 100, ["label"] = "Shopping Bag" },
			[38] = { ["object"] = "prop_cs_vial_01", ["price"] = 100, ["label"] = "Vial" },
			[39] = { ["object"] = "prop_defilied_ragdoll_01", ["price"] = 100, ["label"] = "Ragdoll" }, 
			[40] = { ["object"] = "v_res_fa_book03", ["price"] = 100, ["label"] = "Book" },
			[41] = { ["object"] = "prop_weight_rack_02", ["price"] = 500, ["label"] = "Dumbbell Rack" },
			[42] = { ["object"] = "prop_weight_bench_02", ["price"] = 500, ["label"] = "Bench Press Set" },
			[43] = { ["object"] = "prop_tool_broom", ["price"] = 100, ["label"] = "Broom" },
			[44] = { ["object"] = "prop_fire_exting_2a", ["price"] = 100, ["label"] = "Fire Extinguisher" },
			[45] = { ["object"] = "v_res_vacuum", ["price"] = 100, ["label"] = "Vaccum Cleaner" },
			[46] = { ["object"] = "v_ret_gc_fan", ["price"] = 100, ["label"] = "Ventilator" },
			[47] = { ["object"] = "prop_paint_stepl01b", ["price"] = 100, ["label"] = "Ladder" },
			[48] = { ["object"] = "bkr_prop_weed_bucket_01b", ["price"] = 100, ["label"] = "Fertilizer" },
			[49] = { ["object"] = "v_club_vusnaketank", ["price"] = 500, ["label"] = "Terrarium" },
			[50] = { ["object"] = "prop_pooltable_02", ["price"] = 1500, ["label"] = "Pooltafel" },
			[51] = { ["object"] = "prop_pool_rack_02", ["price"] = 100, ["label"] = "Poolcues" },
			[52] = { ["object"] = "v_club_vu_deckcase", ["price"] = 1000, ["label"] = "DJ Set" },
			[53] = { ["object"] = "v_corp_servercln", ["price"] = 1000, ["label"] = "serverrack" },
			[54] = { ["object"] = "ba_prop_battle_crate_art_02_bc", ["price"] = 5000, ["label"] = "Stolen Art" },
			[55] = { ["object"] = "ba_prop_battle_crate_m_antiques", ["price"] = 5000, ["label"] = "Stolen Art 2" },
			[55] = { ["object"] = "ba_prop_battle_crate_m_jewellery", ["price"] = 5000, ["label"] = "Stolen Jewelry" }
		},
	},
	["general4"] = {
		label = "Random 2",
		items = {
			[1] = { ["object"] = "prop_dummy_01", ["price"] = 100, ["label"] = "Dummy" },
			[2] = { ["object"] = "prop_egg_clock_01", ["price"] = 100, ["label"] = "Egg Clock" },
			[3] = { ["object"] = "prop_el_guitar_01", ["price"] = 100, ["label"] = "E Guitar 1" },
			[4] = { ["object"] = "prop_el_guitar_02", ["price"] = 100, ["label"] = "E Guitar 2" },
			[5] = { ["object"] = "prop_el_guitar_03", ["price"] = 100, ["label"] = "E Guitar 2" },
			[6] = { ["object"] = "prop_feed_sack_01", ["price"] = 100, ["label"] = "Feed Sack" },
			[7] = { ["object"] = "prop_floor_duster_01", ["price"] = 100, ["label"] = "Floor Duster" },
			[8] = { ["object"] = "prop_fruit_basket", ["price"] = 100, ["label"] = "Fruit Basket" },
			[9] = { ["object"] = "prop_f_duster_02", ["price"] = 100, ["label"] = "Duster" },
			[10] = { ["object"] = "prop_grapes_02", ["price"] = 100, ["label"] = "Grapes" },
			[11] = { ["object"] = "prop_hotel_clock_01", ["price"] = 100, ["label"] = "Hotel Clock" },
			[12] = { ["object"] = "prop_idol_case_01", ["price"] = 100, ["label"] = "Idol Case" },
			[13] = { ["object"] = "prop_jewel_02a", ["price"] = 100, ["label"] = "Jewels" },
			[14] = { ["object"] = "prop_jewel_02b", ["price"] = 100, ["label"] = "Jewels" },
			[15] = { ["object"] = "prop_jewel_02c", ["price"] = 100, ["label"] = "Jewels" },
			[16] = { ["object"] = "prop_jewel_03a", ["price"] = 100, ["label"] = "Jewels" },
			[17] = { ["object"] = "prop_jewel_03b", ["price"] = 100, ["label"] = "Jewels" },
			[18] = { ["object"] = "prop_jewel_04a", ["price"] = 100, ["label"] = "Jewels" },
			[19] = { ["object"] = "prop_jewel_04b", ["price"] = 100, ["label"] = "Jewels" },
			[20] = { ["object"] = "prop_j_disptray_01", ["price"] = 100, ["label"] = "Display Tray" },
			[21] = { ["object"] = "prop_j_disptray_01b", ["price"] = 100, ["label"] = "Display Tray" },
			[22] = { ["object"] = "prop_j_disptray_02", ["price"] = 100, ["label"] = "Display Tray" },
			[23] = { ["object"] = "prop_j_disptray_03", ["price"] = 100, ["label"] = "Display Tray" },
			[24] = { ["object"] = "prop_j_disptray_04", ["price"] = 100, ["label"] = "Display Tray" },
			[25] = { ["object"] = "prop_j_disptray_04b", ["price"] = 100, ["label"] = "Display Tray" },
			[26] = { ["object"] = "prop_j_disptray_05", ["price"] = 100, ["label"] = "Display Tray" },
			[27] = { ["object"] = "prop_j_disptray_05b", ["price"] = 100, ["label"] = "Display Tray" },
			[28] = { ["object"] = "prop_ld_greenscreen_01", ["price"] = 100, ["label"] = "Green Screen" },
			[29] = { ["object"] = "prop_ld_handbag", ["price"] = 100, ["label"] = "Handbag" },
			[30] = { ["object"] = "prop_ld_jerrycan_01", ["price"] = 100, ["label"] = "Jerry Can" },
			[31] = { ["object"] = "prop_ld_keypad_01", ["price"] = 100, ["label"] = "Keypad 1" },
			[32] = { ["object"] = "prop_ld_keypad_01b", ["price"] = 100, ["label"] = "Keypad 2" },
			[33] = { ["object"] = "prop_ld_suitcase_01", ["price"] = 100, ["label"] = "Suitcase 1" },
			[34] = { ["object"] = "prop_ld_suitcase_02", ["price"] = 100, ["label"] = "Suitcase 2" },
			[35] = { ["object"] = "hei_p_attache_case_shut", ["price"] = 100, ["label"] = "Suitcase 3"},
			[36] = { ["object"] = "prop_mr_rasberryclean", ["price"] = 100, ["label"] = "Rasberry Clean" },
			[37] = { ["object"] = "prop_paper_bag_01", ["price"] = 100, ["label"] = "Paper Bag" },
			[38] = { ["object"] = "prop_shopping_bags01", ["price"] = 100, ["label"] = "Shopping Bags" },
			[39] = { ["object"] = "prop_shopping_bags02", ["price"] = 100, ["label"] = "Shopping Bags 2" },
			[40] = { ["object"] = "prop_yoga_mat_01", ["price"] = 100, ["label"] = "Yoga Mat 1" },
			[41] = { ["object"] = "prop_yoga_mat_02", ["price"] = 100, ["label"] = "Yoga Mat 2" },
			[42] = { ["object"] = "prop_yoga_mat_03", ["price"] = 100, ["label"] = "Yoga Mat 3" },
			[43] = { ["object"] = "p_ld_sax", ["price"] = 100, ["label"] = "Sax" },
			[44] = { ["object"] = "p_ld_soc_ball_01", ["price"] = 100, ["label"] = "Soccer Ball" },
			[45] = { ["object"] = "p_watch_01", ["price"] = 100, ["label"] = "Watch 1" },
			[46] = { ["object"] = "p_watch_02", ["price"] = 100, ["label"] = "Watch 2" },
			[47] = { ["object"] = "p_watch_03", ["price"] = 100, ["label"] = "Watch 3" },
			[48] = { ["object"] = "p_watch_04", ["price"] = 100, ["label"] = "Watch 4" },
			[49] = { ["object"] = "p_watch_05", ["price"] = 100, ["label"] = "Watch 5" },
			[50] = { ["object"] = "p_watch_06", ["price"] = 100, ["label"] = "Watch 6" },
			[51] = { ["object"] = "apa_mp_h_acc_candles_01", ["price"] = 100, ["label"] = "Candle" },
			[52] = { ["object"] = "apa_mp_h_acc_candles_02", ["price"] = 100, ["label"] = "Candle 2" },
			[53] = { ["object"] = "apa_mp_h_acc_candles_04", ["price"] = 100, ["label"] = "Candle 3" },
			[54] = { ["object"] = "apa_mp_h_acc_candles_06", ["price"] = 100, ["label"] = "Candle 4" },
			[55] = { ["object"] = "apa_mp_h_acc_fruitbowl_02", ["price"] = 100, ["label"] = "Fruit Bowl" },
			[56] = { ["object"] = "apa_mp_h_acc_tray_01", ["price"] = 100, ["label"] = "Thingies" },
			[52] = { ["object"] = "apa_mp_h_acc_candles_02", ["price"] = 100, ["label"] = "Candle 2" },
			[53] = { ["object"] = "apa_mp_h_acc_candles_04", ["price"] = 100, ["label"] = "Candle 3" },
			[54] = { ["object"] = "apa_mp_h_acc_candles_06", ["price"] = 100, ["label"] = "Candle 4" },
			[55] = { ["object"] = "apa_mp_h_acc_fruitbowl_02", ["price"] = 100, ["label"] = "Fruit Bowl" },
			[56] = { ["object"] = "apa_mp_h_acc_tray_01", ["price"] = 100, ["label"] = "Thingies" }
		},
	},
	["small"] = {
		label = "Small",
		items = {
			[1] = { ["object"] = "v_res_r_figcat", ["price"] = 300, ["label"] = "Fig Cat" },
			[2] = { ["object"] = "v_res_r_figclown", ["price"] = 300, ["label"] = "Fig Clown" },
			[3] = { ["object"] = "v_res_r_figauth2", ["price"] = 300, ["label"] = "Fig Auth" },
			[4] = { ["object"] = "v_res_r_figfemale", ["price"] = 300, ["label"] = "Fig Female" },
			[5] = { ["object"] = "v_res_r_figflamenco", ["price"] = 300, ["label"] = "Fig Flamenco" },
			[6] = { ["object"] = "v_res_r_figgirl", ["price"] = 300, ["label"] = "Fig Girl" },
			[7] = { ["object"] = "v_res_r_figgirlclown", ["price"] = 300, ["label"] = "Fig Girl Clown" },
			[8] = { ["object"] = "v_res_r_figoblisk", ["price"] = 300, ["label"] = "Fig Oblisk" },
			[9] = { ["object"] = "v_res_r_figpillar", ["price"] = 300, ["label"] = "Fig Pillar" },
			[10] = { ["object"] = "v_res_r_teapot", ["price"] = 300, ["label"] = "Teapot" },
			[11] = { ["object"] = "v_res_sculpt_dec", ["price"] = 300, ["label"] = "Sculpture 1" },
			[12] = { ["object"] = "v_res_sculpt_decd", ["price"] = 300, ["label"] = "Sculpture 2" },
			[13] = { ["object"] = "v_res_sculpt_dece", ["price"] = 300, ["label"] = "Sculpture 3" },
			[14] = { ["object"] = "v_res_sculpt_decf", ["price"] = 300, ["label"] = "Sculpture 4" },
			[15] = { ["object"] = "v_res_skateboard", ["price"] = 300, ["label"] = "Skateboard" },
			[16] = { ["object"] = "v_res_sketchpad", ["price"] = 300, ["label"] = "Sketchpad" },
			[17] = { ["object"] = "v_res_tissues", ["price"] = 300, ["label"] = "Tissues" },
			[18] = { ["object"] = "v_res_tre_basketmess", ["price"] = 300, ["label"] = "Basket" },
			[19] = { ["object"] = "v_res_tre_bin", ["price"] = 300, ["label"] = "Bin" },
			[20] = { ["object"] = "v_res_tre_cushiona", ["price"] = 300, ["label"] = "Cushion 1" },
			[21] = { ["object"] = "v_res_tre_cushionb", ["price"] = 300, ["label"] = "Cushion 2" },
			[22] = { ["object"] = "v_res_tre_cushionc", ["price"] = 300, ["label"] = "Cushion 3" },
			[23] = { ["object"] = "v_res_tre_cushiond", ["price"] = 300, ["label"] = "Cushion 4" },
			[24] = { ["object"] = "v_res_tre_cushnscuzb", ["price"] = 300, ["label"] = "Cushion 5" },
			[25] = { ["object"] = "v_res_tre_cushnscuzd", ["price"] = 300, ["label"] = "Cushion 6" },
			[26] = { ["object"] = "v_res_tre_fruitbowl", ["price"] = 300, ["label"] = "Fruitbowl" },
			[27] = { ["object"] = "v_med_p_sideboard", ["price"] = 300, ["label"] = "Sideboard" },
			[28] = { ["object"] = "prop_idol_01", ["price"] = 100, ["label"] = "Idol 1" },
			[29] = { ["object"] = "v_res_r_fighorsestnd", ["price"] = 300, ["label"] = "Black Horse Figure" },
			[30] = { ["object"] = "v_res_r_fighorse", ["price"] = 300, ["label"] = "Large Horse Statue" },
			[31] = { ["object"] = "v_res_r_figdancer", ["price"] = 300, ["label"] = "Dancer Statue" },
			[32] = { ["object"] = "v_res_fa_idol02", ["price"] = 300, ["label"] = "Elephant Figure" },
			[33] = { ["object"] = "v_res_m_statue", ["price"] = 300, ["label"] = "Sculpture" },
			[34] = { ["object"] = "v_20_ornaeagle", ["price"] = 300, ["label"] = "Eagle Statue" },
			[35] = { ["object"] = "v_med_p_vaseround", ["price"] = 300, ["label"] = "Rounded Vase" },
			[36] = { ["object"] = "ex_mp_h_acc_vase_05", ["price"] = 300, ["label"] = "Purple Vase" },
			[37] = { ["object"] = "apa_mp_h_acc_dec_head_01", ["price"] = 300, ["label"] = "Artwork" },
			[38] = { ["object"] = "apa_mp_h_acc_dec_sculpt_02", ["price"] = 300, ["label"] = "Artwork 2" },
			[39] = { ["object"] = "ex_mp_h_acc_dec_plate_02", ["price"] = 300, ["label"] = "Artwork 3" },
			[40] = { ["object"] = "apa_mp_h_acc_bowl_ceramic_01", ["price"] = 300, ["label"] = "Scale" },
			[41] = { ["object"] = "apa_mp_h_acc_dec_plate_01", ["price"] = 300, ["label"] = "Scale 2" },
			[42] = { ["object"] = "apa_mp_h_acc_vase_01", ["price"] = 300, ["label"] = "Black & White Vase" },
			[43] = { ["object"] = "apa_mp_h_acc_vase_02", ["price"] = 300, ["label"] = "Red Vase" },
			[44] = { ["object"] = "apa_mp_h_acc_vase_05", ["price"] = 300, ["label"] = "Vase" },
			[45] = { ["object"] = "apa_mp_h_acc_vase_06", ["price"] = 300, ["label"] = "Black & White Vase 2" },
			[46] = { ["object"] = "apa_mp_h_acc_dec_plate_01", ["price"] = 300, ["label"] = "Scale 2" }
		},
	},
	["storage"] = {
		label = "Storage",
		items = {
			[1] = { ["object"] = "v_res_cabinet", ["price"] = 2500, ["label"] = "Cabinet Large" },
			[2] = { ["object"] = "v_res_d_dressingtable", ["price"] = 2500, ["label"] = "Dressing Table" },
			[3] = { ["object"] = "v_res_d_sideunit", ["price"] = 2500, ["label"] = "Side Unit" },
			[4] = { ["object"] = "v_res_fh_sidebrddine", ["price"] = 2500, ["label"] = "Side Unit" },
			[5] = { ["object"] = "v_res_fh_sidebrdlngb", ["price"] = 2500, ["label"] = "Side Unit" },
			[6] = { ["object"] = "v_res_mbbedtable", ["price"] = 2500, ["label"] = "Bed Unit" },
			[7] = { ["object"] = "v_res_j_tvstand", ["price"] = 2500, ["label"] = "TV Unit" },
			[8] = { ["object"] = "v_res_mbdresser", ["price"] = 2500, ["label"] = "Dresser Unit" },
			[9] = { ["object"] = "v_res_mbottoman", ["price"] = 2500, ["label"] = "Bottoman Unit" },
			[10] = { ["object"] = "v_res_mconsolemod", ["price"] = 2500, ["label"] = "Console Unit" },
			[11] = { ["object"] = "v_res_mcupboard", ["price"] = 2500, ["label"] = "Cupboard Unit" },
			[12] = { ["object"] = "v_res_mdchest", ["price"] = 2500, ["label"] = "Chest Unit" },
			[13] = { ["object"] = "v_res_msoncabinet", ["price"] = 2500, ["label"] = "Mason Unit" },
			[14] = { ["object"] = "v_res_m_armoire", ["price"] = 2500, ["label"] = "Armoire Unit" },
			[15] = { ["object"] = "v_res_m_sidetable", ["price"] = 2500, ["label"] = "Side Unit" },
			[16] = { ["object"] = "v_res_son_desk", ["price"] = 2500, ["label"] = "Desk Unit" },
			[17] = { ["object"] = "v_res_tre_bedsidetable", ["price"] = 2500, ["label"] = "Side Unit" },
			[18] = { ["object"] = "v_res_tre_bedsidetableb", ["price"] = 2500, ["label"] = "Side Unit 2" },
			[19] = { ["object"] = "v_res_tre_smallbookshelf", ["price"] = 2500, ["label"] = "Book Unit" },
			[20] = { ["object"] = "v_res_tre_storagebox", ["price"] = 2500, ["label"] = "Box Unit" },
			[21] = { ["object"] = "v_res_tre_storageunit", ["price"] = 2500, ["label"] = "Storage Unit" },
			[22] = { ["object"] = "v_res_tre_wardrobe", ["price"] = 2500, ["label"] = "Wardrobe Unit" },
			[23] = { ["object"] = "v_res_tre_wdunitscuz", ["price"] = 2500, ["label"] = "Wood Unit" },
			[24] = { ["object"] = "prop_devin_box_closed", ["price"] = 100, ["label"] = "Bean Bag 1" },
			[25] = { ["object"] = "prop_mil_crate_01", ["price"] = 100, ["label"] = "Mil Crate 1" },
			[26] = { ["object"] = "prop_mil_crate_02", ["price"] = 100, ["label"] = "Mil Crate 2" },
			[27] = { ["object"] = "prop_ld_int_safe_01", ["price"] = 1100, ["label"] = "Safe" },
			[28] = { ["object"] = "prop_toolchest_05", ["price"] = 5000, ["label"] = "Crafting Bench" },
			[29] = { ["object"] = "v_corp_filecablow", ["price"] = 500, ["label"] = "Low Cabinet" },
			[30] = { ["object"] = "v_corp_filecabtall", ["price"] = 500, ["label"] = "High Cabinet" },
			[31] = { ["object"] = "apa_mp_h_str_shelffloorm_02", ["price"] = 500, ["label"] = "Large Modern Closet" },
			[32] = { ["object"] = "v_ilev_frnkwarddr1", ["price"] = 500, ["label"] = "Franklin Wardrobe" },
			[33] = { ["object"] = "prop_coathook_01", ["price"] = 100, ["label"] = "Coat Rack" },
			[34] = { ["object"] = "v_corp_lowcabdark01", ["price"] = 500, ["label"] = "Low Black Cabinet" },
			[35] = { ["object"] = "v_corp_tallcabdark01", ["price"] = 500, ["label"] = "High Black Cabinet" },
			[36] = { ["object"] = "v_corp_cabshelves01", ["price"] = 1000, ["label"] = "Black Cabinet" },
			[37] = { ["object"] = "v_corp_offshelf", ["price"] = 1000, ["label"] = "Large Cabinet" },
			[38] = { ["object"] = "v_61_lng_mesh_unitc", ["price"] = 500, ["label"] = "Bookcase White" },
			[39] = { ["object"] = "ba_wardrobe", ["price"] = 500, ["label"] = "Wardrobe" },
			[40] = { ["object"] = "apa_mp_h_str_sideboardl_06", ["price"] = 750, ["label"] = "Modern Cabinet" },
			[41] = { ["object"] = "apa_mp_h_str_sideboardl_09", ["price"] = 750, ["label"] = "Modern Cabinet 2" },
			[42] = { ["object"] = "apa_mp_h_str_shelfwallm_01", ["price"] = 750, ["label"] = "Bookcase 2" },
			[43] = { ["object"] = "apa_mp_h_str_sideboardl_11", ["price"] = 750, ["label"] = "Modern Cabinet 3" },
			[44] = { ["object"] = "imp_prop_impexp_parts_rack_03a", ["price"] = 750, ["label"] = "Car Parts" },
			[45] = { ["object"] = "imp_prop_impexp_parts_rack_04a", ["price"] = 750, ["label"] = "Car Parts 2" },
			[46] = { ["object"] = "imp_prop_impexp_parts_rack_05a", ["price"] = 750, ["label"] = "Car Parts 3" },
			[47] = { ["object"] = "apa_mp_h_bed_chestdrawer_02", ["price"] = 750, ["label"] = "Chest of Drawers" },
			[48] = { ["object"] = "hei_heist_bed_chestdrawer_04", ["price"] = 750, ["label"] = "Chest of Drawers 2" },
			[49] = { ["object"] = "prop_rub_cabinet", ["price"] = 50, ["label"] = "Rusted Cabinet" },
			[50] = { ["object"] = "prop_tv_cabinet_03", ["price"] = 750, ["label"] = "TV Box" },
			[51] = { ["object"] = "prop_tv_cabinet_04", ["price"] = 750, ["label"] = "TV Box 2" },
			[52] = { ["object"] = "prop_tv_cabinet_05", ["price"] = 750, ["label"] = "TV Box 3" },
			[53] = { ["object"] = "imp_prop_impexp_parts_rack_05a", ["price"] = 750, ["label"] = "Car Parts 3" },
			[54] = { ["object"] = "hei_heist_bed_chestdrawer_04", ["price"] = 750, ["label"] = "Chest of Drawers 2" },
			[55] = { ["object"] = "prop_rub_cabinet", ["price"] = 50, ["label"] = "Rusted Cabinet" },
			[56] = { ["object"] = "prop_tv_cabinet_03", ["price"] = 750, ["label"] = "TV Box" },
			[57] = { ["object"] = "prop_tv_cabinet_04", ["price"] = 750, ["label"] = "TV Box 2" },
			[58] = { ["object"] = "prop_tv_cabinet_05", ["price"] = 750, ["label"] = "TV Box 3" },
			[59] = { ["object"] = "apa_mp_h_str_shelffreel_01", ["price"] = 750, ["label"] = "IKEA Cupboard" },
			[60] = { ["object"] = "apa_mp_h_str_sideboardl_13", ["price"] = 750, ["label"] = "Modern Cabinet 4" },
			[61] = { ["object"] = "apa_mp_h_str_sideboardl_14", ["price"] = 750, ["label"] = "Modern Cabinet 5" },
			[62] = { ["object"] = "apa_mp_h_str_sideboardm_02", ["price"] = 750, ["label"] = "Modern Cabinet 6" }
		},
	},
	["electronics"] = {
		label = "Electronics",
		items = {
			[1] = { ["object"] = "prop_trailr_fridge", ["price"] = 300, ["label"] = "Old Fridge" },
			[2] = { ["object"] = "v_res_fh_speaker", ["price"] = 300, ["label"] = "Speaker" },
			[3] = { ["object"] = "v_res_fh_speakerdock", ["price"] = 300, ["label"] = "Speaker Dock" },
			[4] = { ["object"] = "v_res_fh_bedsideclock", ["price"] = 300, ["label"] = "Bedside Clock" },
			[5] = { ["object"] = "v_res_fa_phone", ["price"] = 300, ["label"] = "Phone" },
			[6] = { ["object"] = "v_res_fh_towerfan", ["price"] = 300, ["label"] = "Tower Fan" },
			[7] = { ["object"] = "v_res_fa_fan", ["price"] = 300, ["label"] = "Fan" },
			[8] = { ["object"] = "v_res_lest_bigscreen", ["price"] = 300, ["label"] = "Bigscreen" },
			[9] = { ["object"] = "v_res_lest_monitor", ["price"] = 300, ["label"] = "Monitor" },
			[10] = { ["object"] = "v_res_tre_mixer", ["price"] = 300, ["label"] = "Mixer" },
			[11] = { ["object"] = "prop_cs_cctv", ["price"] = 100, ["label"] = "CCTV" },
			[12] = { ["object"] = "prop_ld_lap_top", ["price"] = 100, ["label"] = "Laptop" },
			[13] = { ["object"] = "prop_ld_monitor_01", ["price"] = 100, ["label"] = "Monitor" },
			[14] = { ["object"] = "prop_speaker_05", ["price"] = 500, ["label"] = "Mounted Speaker" },
			[15] = { ["object"] = "prop_tv_flat_03b", ["price"] = 1000, ["label"] = "Little Flatscreen" },
			[16] = { ["object"] = "prop_laptop_01a", ["price"] = 750, ["label"] = "Folded Open Paptop" },
			[17] = { ["object"] = "prop_tv_flat_michael", ["price"] = 3000, ["label"] = "Flatscreen Hanging" },
			[18] = { ["object"] = "prop_dyn_pc", ["price"] = 1000, ["label"] = "PC" },
			[19] = { ["object"] = "prop_keyboard_01b", ["price"] = 100, ["label"] = "Keyboard" },
			[20] = { ["object"] = "prop_mouse_01b", ["price"] = 100, ["label"] = "Mouse Computer" },
			[21] = { ["object"] = "v_ret_gc_phone", ["price"] = 100, ["label"] = "Office Phone" },
			[22] = { ["object"] = "prop_tv_flat_01", ["price"] = 5000, ["label"] = "Great Flatscreen" },
			[23] = { ["object"] = "prop_arcade_01", ["price"] = 5000, ["label"] = "Arcade" },
			[24] = { ["object"] = "prop_console_01", ["price"] = 250, ["label"] = "Game Console" },
			[25] = { ["object"] = "v_res_tre_dvdplayer", ["price"] = 250, ["label"] = "DVD Player" },
			[26] = { ["object"] = "prop_speaker_08", ["price"] = 500, ["label"] = "Wooden Speaker" },
			[27] = { ["object"] = "prop_cctv_mon_02", ["price"] = 300, ["label"] = "CCTV Monitor" },
			[28] = { ["object"] = "prop_tv_flat_02", ["price"] = 2500, ["label"] = "Flat Screen Stand" },
			[29] = { ["object"] = "prop_cctv_cam_01a", ["price"] = 300, ["label"] = "CCTV 2" },
			[30] = { ["object"] = "prop_dest_cctv_02", ["price"] = 300, ["label"] = "CCTV Monitor 2" },
			[31] = { ["object"] = "prop_cctv_cam_07a", ["price"] = 300, ["label"] = "CCTV 3" },
			[32] = { ["object"] = "apa_mp_h_str_avunits_04", ["price"] = 5500, ["label"] = "Flat Screen Furniture" },
			[33] = { ["object"] = "apa_mp_h_str_avunits_01", ["price"] = 5500, ["label"] = "Flat Screen Furniture 2" },
			[34] = { ["object"] = "v_club_vu_deckcase", ["price"] = 1000, ["label"] = "DJ Set" },
			[35] = { ["object"] = "v_corp_servercln", ["price"] = 1000, ["label"] = "serverrack" },
			[36] = { ["object"] = "apa_mp_h_str_avunitl_01_b", ["price"] = 5500, ["label"] = "Flat Screen Furniture 3" },
			[37] = { ["object"] = "apa_mp_h_str_avunitl_04", ["price"] = 5500, ["label"] = "Flat Screen Furniture 4" },
			[38] = { ["object"] = "apa_mp_h_str_avunitm_01", ["price"] = 5500, ["label"] = "Flat Screen Furniture 5" },
			[39] = { ["object"] = "apa_mp_h_str_avunitm_03", ["price"] = 5500, ["label"] = "Flat Screen Furniture 6" },
			[40] = { ["object"] = "apa_mp_h_str_avunits_04", ["price"] = 5500, ["label"] = "Flat Screen Furniture 7" },
			[41] = { ["object"] = "v_res_printer", ["price"] = 300, ["label"] = "Printer" },
			[42] = { ["object"] = "apa_mp_h_acc_phone_01", ["price"] = 100, ["label"] = "Old fashion Phone" },
			[43] = { ["object"] = "v_res_mousemat", ["price"] = 300, ["label"] = "Mouse Mat" },
			[44] = { ["object"] = "v_res_pcheadset", ["price"] = 300, ["label"] = "Headset" },
			[45] = { ["object"] = "v_res_pcspeaker", ["price"] = 300, ["label"] = "PC Speaker" },
			[46] = { ["object"] = "v_res_pcwoofer", ["price"] = 300, ["label"] = "PC Subwoofer" },
			[47] = { ["object"] = "ba_prop_battle_club_speaker_small", ["price"] = 500, ["label"] = "Little Box" },
			[48] = { ["object"] = "ba_prop_battle_club_speaker_med", ["price"] = 750, ["label"] = "Box" },
			[49] = { ["object"] = "ba_prop_battle_club_speaker_large", ["price"] = 1000, ["label"] = "Great Box" },
			[50] = { ["object"] = "v_res_pcspeaker", ["price"] = 300, ["label"] = "PC Speaker" },
			[51] = { ["object"] = "v_res_pcwoofer", ["price"] = 300, ["label"] = "PC Subwoofer" }
		},
	},
	["lighting"] = {
		label = "Lighting",
		items = {
			[1] = { ["object"] = "v_corp_cd_desklamp", ["price"] = 100, ["label"] = "Desk Corp Lamp" },
			[2] = { ["object"] = "v_res_desklamp", ["price"] = 100, ["label"] = "Desk Lamp" },
			[3] = { ["object"] = "v_res_d_lampa", ["price"] = 100, ["label"] = "Lamp AA" },
			[4] = { ["object"] = "v_res_fa_lamp1on", ["price"] = 100, ["label"] = "Lamp 1" },
			[5] = { ["object"] = "v_res_fh_floorlamp", ["price"] = 100, ["label"] = "Floor Lamp" },
			[6] = { ["object"] = "v_res_fh_lampa_on", ["price"] = 100, ["label"] = "Lamp 2" },
			[7] = { ["object"] = "v_res_j_tablelamp1", ["price"] = 100, ["label"] = "Table Lamp" },
			[8] = { ["object"] = "v_res_j_tablelamp2", ["price"] = 100, ["label"] = "Table Lamp 2" },
			[9] = { ["object"] = "v_res_mdbedlamp", ["price"] = 100, ["label"] = "Bed Lamp" },
			[10] = { ["object"] = "v_res_mplanttongue", ["price"] = 100, ["label"] = "Plant Tongue Lamp" },
			[11] = { ["object"] = "v_res_mtblelampmod", ["price"] = 100, ["label"] = "Table Lamp 3" },
			[12] = { ["object"] = "v_res_m_lampstand", ["price"] = 100, ["label"] = "Lamp Stand" },
			[13] = { ["object"] = "v_res_m_lampstand2", ["price"] = 100, ["label"] = "Lamp Stand 2" },
			[14] = { ["object"] = "v_res_m_lamptbl", ["price"] = 100, ["label"] = "Table Lamp 4" },
			[15] = { ["object"] = "v_res_tre_lightfan", ["price"] = 100, ["label"] = "Light Fan" },
			[16] = { ["object"] = "v_res_tre_talllamp", ["price"] = 100, ["label"] = "Tall Lamp" },
			[17] = { ["object"] = "v_ret_fh_walllighton", ["price"] = 100, ["label"] = "Wall Light" },
			[18] = { ["object"] = "v_ret_gc_lamp", ["price"] = 100, ["label"] = "GC Lamp" },
			[19] = { ["object"] = "prop_dummy_light", ["price"] = 100, ["label"] = "Flickering Light" },
			[20] = { ["object"] = "prop_ld_cont_light_01", ["price"] = 100, ["label"] = "Side Wall Light" },
			[21] = { ["object"] = "V_44_D_emis", ["price"] = 100, ["label"] = "Test Light" },
			[22] = { ["object"] = "prop_wall_light_07a", ["price"] = 100, ["label"] = "Lantern" },
			[23] = { ["object"] = "prop_wall_light_01a", ["price"] = 100, ["label"] = "Lamp" },
			[24] = { ["object"] = "v_serv_tu_light2_", ["price"] = 100, ["label"] = "Industrial Light" },
			[25] = { ["object"] = "v_serv_tu_light3_", ["price"] = 100, ["label"] = "Industrial Light 2" },
			[26] = { ["object"] = "ba_prop_battle_lights_ceiling_l_a", ["price"] = 300, ["label"] = "Pendant Lamp" },
			[27] = { ["object"] = "v_med_p_floorlamp", ["price"] = 300, ["label"] = "Great Lamp" },
			[28] = { ["object"] = "v_club_vu_lamp", ["price"] = 100, ["label"] = "Little Lamp" },
			[29] = { ["object"] = "ba_prop_battle_lights_wall_l_a", ["price"] = 100, ["label"] = "Wall Lamp" },
			[30] = { ["object"] = "ba_prop_battle_lights_ceiling_l_c", ["price"] = 300, ["label"] = "Pendant Lamp 2" },
			[31] = { ["object"] = "ba_prop_battle_lights_ceiling_l_b", ["price"] = 300, ["label"] = "Chandelier 2" },
			[32] = { ["object"] = "ba_prop_battle_lights_wall_l_c", ["price"] = 100, ["label"] = "Wall Lamp 2" },
			[33] = { ["object"] = "ba_prop_battle_lights_wall_l_b", ["price"] = 100, ["label"] = "Wall Lamp 3" },
			[34] = { ["object"] = "hei_heist_lit_lightpendant_02", ["price"] = 300, ["label"] = "Pendant Lamp 3" },
			[35] = { ["object"] = "prop_oldlight_01b", ["price"] = 100, ["label"] = "Wall Lamp 4" },
			[36] = { ["object"] = "apa_mp_h_lit_floorlampnight_07", ["price"] = 100, ["label"] = "Blue Lamp" },
			[37] = { ["object"] = "apa_mp_h_ceiling_light_01", ["price"] = 100, ["label"] = "Commercial" },
			[38] = { ["object"] = "apa_mp_h_ceiling_light_01_day", ["price"] = 100, ["label"] = "Commercial 2" },
			[39] = { ["object"] = "apa_mp_h_ceiling_light_02", ["price"] = 100, ["label"] = "Ceiling Light" },
			[40] = { ["object"] = "apa_mp_h_ceiling_light_02_day", ["price"] = 100, ["label"] = "Ceiling Light 2" },
			[41] = { ["object"] = "ba_prop_battle_lights_ceiling_l_d", ["price"] = 100, ["label"] = "Commercial 3" },
			[42] = { ["object"] = "ba_prop_battle_lights_ceiling_l_f", ["price"] = 100, ["label"] = "Ceiling Light 3" },
			[43] = { ["object"] = "ba_prop_battle_lights_ceiling_l_e", ["price"] = 100, ["label"] = "Ceiling Light 4" },
			[44] = { ["object"] = "apa_mp_h_floorlamp_a", ["price"] = 100, ["label"] = "Floor Lamp" },
			[45] = { ["object"] = "apa_mp_h_floorlamp_b", ["price"] = 100, ["label"] = "Floor Lamp 2" },
			[46] = { ["object"] = "apa_mp_h_floorlamp_c", ["price"] = 100, ["label"] = "Floor Lamp 3" },
			[47] = { ["object"] = "apa_mp_h_floor_lamp_int_08", ["price"] = 100, ["label"] = "Floor Lamp 4" },
			[48] = { ["object"] = "apa_mp_h_lampbulb_multiple_a", ["price"] = 100, ["label"] = "Ceiling Light 5" },
			[49] = { ["object"] = "apa_mp_h_lit_floorlamp_02", ["price"] = 100, ["label"] = "Floor Lamp 5" },
			[50] = { ["object"] = "apa_mp_h_lit_floorlampnight_14", ["price"] = 100, ["label"] = "Floor Lamp 6" },
			[51] = { ["object"] = "apa_mp_h_lit_floorlamp_03", ["price"] = 100, ["label"] = "Floor Lamp 7" },
			[52] = { ["object"] = "apa_mp_h_lit_floorlamp_06", ["price"] = 100, ["label"] = "Floor Lamp 8" },
			[53] = { ["object"] = "apa_mp_h_lit_floorlamp_10", ["price"] = 100, ["label"] = "Floor Lamp 9" },
			[54] = { ["object"] = "apa_mp_h_lit_floorlamp_13", ["price"] = 100, ["label"] = "Floor Lamp 10" },
			[55] = { ["object"] = "apa_mp_h_lit_floorlamp_17", ["price"] = 100, ["label"] = "Floor Lamp 11" },
			[56] = { ["object"] = "apa_mp_h_lit_lamptablenight_16", ["price"] = 100, ["label"] = "Night Light" },
			[57] = { ["object"] = "apa_mp_h_lit_lamptablenight_24", ["price"] = 100, ["label"] = "Night Light 2" },
			[58] = { ["object"] = "apa_mp_h_lit_lamptable_005", ["price"] = 100, ["label"] = "Night Light 3" },
			[59] = { ["object"] = "apa_mp_h_lit_lamptable_04", ["price"] = 100, ["label"] = "Night Light 4" },
			[60] = { ["object"] = "apa_mp_h_lit_lamptable_09", ["price"] = 100, ["label"] = "Night Light 5" },
			[61] = { ["object"] = "apa_mp_h_lit_lamptable_14", ["price"] = 100, ["label"] = "Night Light 6" },
			[62] = { ["object"] = "apa_mp_h_lit_lamptable_17", ["price"] = 100, ["label"] = "Night Light 7" },
			[63] = { ["object"] = "apa_mp_h_yacht_table_lamp_01", ["price"] = 100, ["label"] = "Night Light 8" }
			
		},
	},
	["tables"] = {
		label = "Tables",
		items = {
			[1] = { ["object"] = "v_res_d_coffeetable", ["price"] = 500, ["label"] = "Coffee Table 1" },
			[2] = { ["object"] = "v_res_d_roundtable", ["price"] = 500, ["label"] = "Round Table" },
			[3] = { ["object"] = "v_res_d_smallsidetable", ["price"] = 500, ["label"] = "Small Side Table" },
			[4] = { ["object"] = "v_res_fh_coftablea", ["price"] = 500, ["label"] = "Table A" },
			[5] = { ["object"] = "v_res_fh_coftableb", ["price"] = 500, ["label"] = "Table B" },
			[6] = { ["object"] = "v_res_fh_coftbldisp", ["price"] = 500, ["label"] = "Table C" },
			[7] = { ["object"] = "v_res_fh_diningtable", ["price"] = 500, ["label"] = "Dining Table" },
			[8] = { ["object"] = "v_res_j_coffeetable", ["price"] = 500, ["label"] = "Coffee Table 2" },
			[9] = { ["object"] = "v_res_j_lowtable", ["price"] = 500, ["label"] = "Low Table" },
			[10] = { ["object"] = "v_res_mdbedtable", ["price"] = 500, ["label"] = "Bed Table" },
			[11] = { ["object"] = "v_res_mddesk", ["price"] = 500, ["label"] = "Desk" },
			[12] = { ["object"] = "v_res_msidetblemod", ["price"] = 500, ["label"] = "Side Table" },
			[13] = { ["object"] = "v_res_m_console", ["price"] = 500, ["label"] = "Console Table" },
			[14] = { ["object"] = "v_res_m_dinetble_replace", ["price"] = 500, ["label"] = "Dining Table 2" },
			[15] = { ["object"] = "v_res_m_h_console", ["price"] = 500, ["label"] = "Console H Table" },
			[16] = { ["object"] = "v_res_m_stool", ["price"] = 500, ["label"] = "Stool?" },
			[17] = { ["object"] = "v_res_tre_sideboard", ["price"] = 500, ["label"] = "Sideboard Table" },
			[18] = { ["object"] = "v_res_tre_table2", ["price"] = 500, ["label"] = "Table 2" },
			[19] = { ["object"] = "v_res_tre_tvstand", ["price"] = 500, ["label"] = "TV Table" },
			[20] = { ["object"] = "v_res_tre_tvstand_tall", ["price"] = 500, ["label"] = "TV Table Tall" },
			[21] = { ["object"] = "v_med_p_coffeetable", ["price"] = 500, ["label"] = "Med Coffee Table" },
			[22] = { ["object"] = "v_med_p_desk", ["price"] = 500, ["label"] = "Med Desk" },
			[23] = { ["object"] = "prop_yacht_table_01", ["price"] = 100, ["label"] = "Yacht Table 1" },
			[24] = { ["object"] = "prop_yacht_table_02", ["price"] = 100, ["label"] = "Yacht Table 2" },
			[25] = { ["object"] = "prop_yacht_table_03", ["price"] = 100, ["label"] = "Yacht Table 3" },
			[26] = { ["object"] = "v_ret_csr_table", ["price"] = 100, ["label"] = "CSR Table" },
			[27] = { ["object"] = "v_res_mconsoletrad", ["price"] = 250, ["label"] = "High Side Table" },
			[28] = { ["object"] = "v_ilev_liconftable_sml", ["price"] = 500, ["label"] = "Conference Table" },
			[29] = { ["object"] = "v_ret_tablesml", ["price"] = 350, ["label"] = "Side Table Marillaux" },
			[30] = { ["object"] = "apa_mp_h_yacht_coffee_table_02", ["price"] = 500, ["label"] = "Coffee Brown Table" },
			[31] = { ["object"] = "apa_mp_h_yacht_side_table_01", ["price"] = 300, ["label"] = "Side Brown Table" },
			[32] = { ["object"] = "apa_mp_h_yacht_side_table_02", ["price"] = 300, ["label"] = "Rounded Side Table" },
			[33] = { ["object"] = "apa_mp_h_tab_sidelrg_04", ["price"] = 300, ["label"] = "Rounded Side Table 2" },
			[34] = { ["object"] = "v_club_vu_table", ["price"] = 300, ["label"] = "Set Table" },
			[35] = { ["object"] = "apa_mp_h_tab_sidelrg_07", ["price"] = 500, ["label"] = "Coffee Glass Table" },
			[36] = { ["object"] = "bkr_prop_weed_table_01b", ["price"] = 100, ["label"] = "Folding Table" },
			[37] = { ["object"] = "ba_prop_int_trad_table", ["price"] = 300, ["label"] = "Standing Table" },
			[38] = { ["object"] = "apa_mp_h_str_sideboards_02", ["price"] = 750, ["label"] = "Side Glass Table" },
			[39] = { ["object"] = "apa_mp_h_yacht_coffee_table_01", ["price"] = 750, ["label"] = "Modern Coffee Table" },
			[40] = { ["object"] = "apa_mp_h_din_table_04", ["price"] = 1000, ["label"] = "Dining Glass Table" },
			[41] = { ["object"] = "xm_prop_base_staff_desk_01", ["price"] = 5000, ["label"] = "Desk + Setup" },
			[42] = { ["object"] = "apa_mp_h_tab_coffee_07", ["price"] = 1000, ["label"] = "Triangular Side Table" },
			[43] = { ["object"] = "apa_mp_h_tab_coffee_08", ["price"] = 1000, ["label"] = "White Side Table" },
			[44] = { ["object"] = "apa_mp_h_tab_sidelrg_01", ["price"] = 1000, ["label"] = "Glass Side Table" },
			[45] = { ["object"] = "apa_mp_h_tab_sidelrg_02", ["price"] = 1000, ["label"] = "Glass Side Table 2" },
			[46] = { ["object"] = "apa_mp_h_tab_sidesml_01", ["price"] = 1000, ["label"] = "Folding Table" },
			[47] = { ["object"] = "apa_mp_h_tab_sidesml_01", ["price"] = 1000, ["label"] = "Cube Side Table" },
			[42] = { ["object"] = "ba_prop_int_edgy_table_01", ["price"] = 500, ["label"] = "Marble Table" },
			[43] = { ["object"] = "ba_prop_int_edgy_table_02", ["price"] = 500, ["label"] = "High Marble Table" },
			[44] = { ["object"] = "apa_mp_h_tab_sidelrg_01", ["price"] = 1000, ["label"] = "Glass Side Table" },
		},
	},
	["plants"] = {
		label = "Plants",
		items = {
			[1] = { ["object"] = "prop_fib_plant_01", ["price"] = 150, ["label"] = "Plant Fib" },
			[2] = { ["object"] = "v_corp_bombplant", ["price"] = 170, ["label"] = "Plant Bomb" },		
			[3] = { ["object"] = "v_res_mflowers", ["price"] = 170, ["label"] = "Plant Flowers" },	
			[4] = { ["object"] = "v_res_mvasechinese", ["price"] = 170, ["label"] = "Plant Chinese" },	
			[5] = { ["object"] = "v_res_m_bananaplant", ["price"] = 170, ["label"] = "Plant Banana" },	
			[6] = { ["object"] = "v_res_m_palmplant1", ["price"] = 170, ["label"] = "Plant Palm" },	
			[7] = { ["object"] = "v_res_m_palmstairs", ["price"] = 170, ["label"] = "Plant Palm 2" },	
			[8] = { ["object"] = "v_res_m_urn", ["price"] = 170, ["label"] = "Plant Urn" },	
			[9] = { ["object"] = "v_res_rubberplant", ["price"] = 170, ["label"] = "Plant Rubber" },	
			[10] = { ["object"] = "v_res_tre_plant", ["price"] = 170, ["label"] = "Plant" },	
			[11] = { ["object"] = "v_res_tre_tree", ["price"] = 170, ["label"] = "Plant Tree" },	
			[12] = { ["object"] = "v_med_p_planter", ["price"] = 170, ["label"] = "Planter" },	
			[13] = { ["object"] = "v_ret_flowers", ["price"] = 100, ["label"] = "Flowers" },
			[14] = { ["object"] = "v_ret_j_flowerdisp", ["price"] = 100, ["label"] = "Flowers 1" },
			[15] = { ["object"] = "v_ret_j_flowerdisp_white", ["price"] = 100, ["label"] = "Flowers 2" },	
			[16] = { ["object"] = "v_res_m_vasefresh", ["price"] = 300, ["label"] = "Flower Vase" },
			[17] = { ["object"] = "v_res_rosevasedead", ["price"] = 300, ["label"] = "rozenvaas 2" },
			[18] = { ["object"] = "v_res_exoticvase", ["price"] = 300, ["label"] = "Flower Vase 2" },
			[19] = { ["object"] = "v_res_rosevase", ["price"] = 300, ["label"] = "Rose Vase" },
			[20] = { ["object"] = "prop_pot_plant_6a", ["price"] = 300, ["label"] = "Hanging Plant" },
			[21] = { ["object"] = "prop_pot_plant_02a", ["price"] = 300, ["label"] = "Plant Pot" },
			[20] = { ["object"] = "apa_mp_h_acc_plant_palm_01", ["price"] = 300, ["label"] = "Palm Plant" },
			[21] = { ["object"] = "prop_plant_interior_05a", ["price"] = 300, ["label"] = "Flower Box" },
			[22] = { ["object"] = "prop_plant_int_01a", ["price"] = 300, ["label"] = "Plant" },
			[23] = { ["object"] = "prop_plant_int_01b", ["price"] = 300, ["label"] = "Plant 2" },
			[24] = { ["object"] = "prop_plant_int_02a", ["price"] = 300, ["label"] = "Plant 3" },
			[25] = { ["object"] = "prop_plant_int_02b", ["price"] = 300, ["label"] = "Plant 4" },
			[26] = { ["object"] = "prop_plant_int_03a", ["price"] = 300, ["label"] = "Plant 5" },
			[27] = { ["object"] = "prop_plant_int_03b", ["price"] = 300, ["label"] = "Plant 6" },
			[28] = { ["object"] = "prop_plant_int_03c", ["price"] = 300, ["label"] = "Plant 7" },
			[29] = { ["object"] = "prop_plant_int_04a", ["price"] = 300, ["label"] = "Plant 8" },
			[30] = { ["object"] = "prop_plant_int_04c", ["price"] = 300, ["label"] = "Plant 9" },
			[31] = { ["object"] = "prop_plant_int_05b", ["price"] = 300, ["label"] = "Flower Box 2" },
			[32] = { ["object"] = "prop_pot_plant_01a", ["price"] = 300, ["label"] = "Plant Pot 2" },
			[33] = { ["object"] = "prop_pot_plant_01b", ["price"] = 300, ["label"] = "Plant Pot 3" },
			[34] = { ["object"] = "prop_pot_plant_01c", ["price"] = 300, ["label"] = "Plant Pot 4" },
			[35] = { ["object"] = "prop_pot_plant_01d", ["price"] = 300, ["label"] = "Plant Pot 5" },
			[36] = { ["object"] = "prop_pot_plant_01e", ["price"] = 300, ["label"] = "Plant Pot 6" },
			[37] = { ["object"] = "prop_pot_plant_03b", ["price"] = 300, ["label"] = "Plant Pot 7" },
			[38] = { ["object"] = "prop_pot_plant_05a", ["price"] = 300, ["label"] = "Plant Pot 8" },
			[39] = { ["object"] = "prop_pot_plant_05b", ["price"] = 300, ["label"] = "Plant Pot 9" },
			[40] = { ["object"] = "p_int_jewel_plant_01", ["price"] = 300, ["label"] = "Plant Pot 10" },
			[41] = { ["object"] = "p_int_jewel_plant_02", ["price"] = 300, ["label"] = "Plant Pot 11" },
			[42] = { ["object"] = "apa_mp_h_acc_vase_flowers_01", ["price"] = 300, ["label"] = "Plant Pot 12" },
			[43] = { ["object"] = "apa_mp_h_acc_vase_flowers_02", ["price"] = 300, ["label"] = "Plant Pot 13" },
			[44] = { ["object"] = "apa_mp_h_acc_vase_flowers_03", ["price"] = 300, ["label"] = "Plant Pot 14" },
			[45] = { ["object"] = "apa_mp_h_acc_vase_flowers_04", ["price"] = 300, ["label"] = "Plant Pot 15" }
		},
	},
	["kitchen"] = {
		label = "Kitchen",
		items = {
			[1] = { ["object"] = "prop_washer_01", ["price"] = 150, ["label"] = "Washer 1" },
			[2] = { ["object"] = "prop_washer_02", ["price"] = 150, ["label"] = "Washer 2" },
			[3] = { ["object"] = "prop_washer_03", ["price"] = 150, ["label"] = "Washer 3" },
			[4] = { ["object"] = "prop_washing_basket_01", ["price"] = 150, ["label"] = "Washing Basket" },
			[5] = { ["object"] = "v_res_fridgemoda", ["price"] = 150, ["label"] = "Fridge 1" },
			[6] = { ["object"] = "v_res_fridgemodsml", ["price"] = 150, ["label"] = "Fridge 2" },
			[7] = { ["object"] = "prop_fridge_01", ["price"] = 150, ["label"] = "Fridge 3" },
			[8] = { ["object"] = "prop_fridge_03", ["price"] = 150, ["label"] = "Fridge 4" },
			[9] = { ["object"] = "prop_cooker_03", ["price"] = 150, ["label"] = "Cooker" },
			[10] = { ["object"] = "prop_micro_01", ["price"] = 150, ["label"] = "Microwave 1" },
			[11] = { ["object"] = "prop_micro_02", ["price"] = 150, ["label"] = "Microwave 2" },
			[12] = { ["object"] = "prop_wok", ["price"] = 150, ["label"] = "Wok" },
			[13] = { ["object"] = "v_res_cakedome", ["price"] = 150, ["label"] = "Cake Plate" },
			[14] = { ["object"] = "v_res_fa_chopbrd", ["price"] = 150, ["label"] = "Chopping Board" },
			[15] = { ["object"] = "v_res_mutensils", ["price"] = 150, ["label"] = "Utensils" },
			[16] = { ["object"] = "v_res_pestle", ["price"] = 150, ["label"] = "Pestle" },
			[17] = { ["object"] = "v_ret_ta_paproll", ["price"] = 150, ["label"] = "Roll Paper 1" },
			[18] = { ["object"] = "v_ret_ta_paproll2", ["price"] = 150, ["label"] = "Roll Paper 2" },
			[19] = { ["object"] = "v_ret_fh_pot01", ["price"] = 150, ["label"] = "Pot 1" },
			[20] = { ["object"] = "v_ret_fh_pot02", ["price"] = 150, ["label"] = "Pot 2" },
			[21] = { ["object"] = "v_ret_fh_pot05", ["price"] = 150, ["label"] = "Pot 3" },
			[22] = { ["object"] = "prop_pot_03", ["price"] = 150, ["label"] = "Pot 4" },
			[23] = { ["object"] = "prop_pot_04", ["price"] = 150, ["label"] = "Pot 5" },
			[24] = { ["object"] = "prop_pot_05", ["price"] = 150, ["label"] = "Pot 6" },
			[25] = { ["object"] = "prop_pot_06", ["price"] = 150, ["label"] = "Pot 7" },
			[26] = { ["object"] = "prop_pot_rack", ["price"] = 150, ["label"] = "Pot Rack" },
			[27] = { ["object"] = "prop_kitch_juicer", ["price"] = 150, ["label"] = "Juicer" },
			[28] = { ["object"] = "v_res_ovenhobmod", ["price"] = 1000, ["label"] = "Stove" },
			[29] = { ["object"] = "v_res_mkniferack", ["price"] = 100, ["label"] = "Knives" },
			[30] = { ["object"] = "v_res_mchopboard", ["price"] = 100, ["label"] = "Cutting Board" },
			[31] = { ["object"] = "prop_cs_kitchen_cab_l", ["price"] = 750, ["label"] = "Kitchen Cabinet Wide" },
			[32] = { ["object"] = "prop_cs_kitchen_cab_r", ["price"] = 500, ["label"] = "Kitchen Cabinet" },
			[33] = { ["object"] = "prop_cs_kitchen_cab_r", ["price"] = 500, ["label"] = "Kitchen Cabinet" },
			[34] = { ["object"] = "v_res_tre_fridge", ["price"] = 500, ["label"] = "Fridge" },
			[35] = { ["object"] = "apa_mp_h_acc_coffeemachine_01", ["price"] = 500, ["label"] = "Coffee Machine" }
		},
	},
	["bathroom"] = {
		label = "Bathroom",
		items = {
			[1] = { ["object"] = "prop_ld_toilet_01", ["price"] = 100, ["label"] = "Toilet 1" },
			[2] = { ["object"] = "prop_toilet_01", ["price"] = 100, ["label"] = "Toilet 2" },
			[3] = { ["object"] = "prop_toilet_02", ["price"] = 100, ["label"] = "Toilet 3" },
			[4] = { ["object"] = "prop_sink_02", ["price"] = 100, ["label"] = "Sink 1" },
			[5] = { ["object"] = "prop_sink_04", ["price"] = 100, ["label"] = "Sink 2" },
			[6] = { ["object"] = "prop_sink_05", ["price"] = 100, ["label"] = "Sink 3" },
			[7] = { ["object"] = "prop_sink_06", ["price"] = 100, ["label"] = "Sink 4" },
			[8] = { ["object"] = "prop_soap_disp_01", ["price"] = 100, ["label"] = "Soap Dispenser" },
			[9] = { ["object"] = "prop_shower_rack_01", ["price"] = 100, ["label"] = "Shower Rack" },
			[10] = { ["object"] = "prop_handdry_01", ["price"] = 100, ["label"] = "Hand Dryer 1" },
			[11] = { ["object"] = "prop_handdry_02", ["price"] = 100, ["label"] = "Hand Dryer 2" },
			[12] = { ["object"] = "prop_towel_rail_01", ["price"] = 100, ["label"] = "Towel Rail 1" },
			[13] = { ["object"] = "prop_towel_rail_02", ["price"] = 100, ["label"] = "Towel Rail 2" },
			[14] = { ["object"] = "prop_towel_01", ["price"] = 100, ["label"] = "Towel 1" },
			[15] = { ["object"] = "v_res_mbtowel", ["price"] = 100, ["label"] = "Towel 2" },
			[16] = { ["object"] = "v_res_mbtowelfld", ["price"] = 100, ["label"] = "Towel 3" },
			[17] = { ["object"] = "v_res_mbath", ["price"] = 100, ["label"] = "Bath" },
			[18] = { ["object"] = "v_res_mbsink", ["price"] = 100, ["label"] = "Sink" },
			[19] = { ["object"] = "v_ilev_mm_faucet", ["price"] = 100, ["label"] = "Crane" },
			[20] = { ["object"] = "v_res_tre_washbasket", ["price"] = 250, ["label"] = "Laundry Basket" },
			[21] = { ["object"] = "prop_toilet_soap_02", ["price"] = 100, ["label"] = "Bowl of Soap" },
			[22] = { ["object"] = "prop_bar_sink_01", ["price"] = 100, ["label"] = "Sink" },
			[23] = { ["object"] = "apa_mp_h_bathtub_01", ["price"] = 1000, ["label"] = "Bathtub" }
		}
	},
	["medical"] = {
		label = "Medical",
		items = {
			[1] = { ["object"] = "v_med_barrel", ["price"] = 750, ["label"] = "Barrel" },
			[2] = { ["object"] = "v_med_apecrate", ["price"] = 750, ["label"] = "Ape Crate" },
			[3] = { ["object"] = "v_med_apecratelrg", ["price"] = 750, ["label"] = "Ape Crate Large" },
			[4] = { ["object"] = "v_med_bed1", ["price"] = 750, ["label"] = "Bed 1" },
			[5] = { ["object"] = "v_med_bed2", ["price"] = 750, ["label"] = "Bed 2" },
			[6] = { ["object"] = "v_med_bedtable", ["price"] = 750, ["label"] = "Bed Table" },
			[7] = { ["object"] = "v_med_bench1", ["price"] = 750, ["label"] = "Bench 1" },
			[8] = { ["object"] = "v_med_bench2", ["price"] = 750, ["label"] = "Bench 2" },
			[9] = { ["object"] = "v_med_benchcentr", ["price"] = 750, ["label"] = "Bench Center" },
			[10] = { ["object"] = "v_med_benchset1", ["price"] = 750, ["label"] = "Bench Set" },
			[11] = { ["object"] = "v_med_bigtable", ["price"] = 750, ["label"] = "Big Table" },
			[12] = { ["object"] = "v_med_bin", ["price"] = 150, ["label"] = "Bin" },
			[13] = { ["object"] = "v_med_centrifuge1", ["price"] = 750, ["label"] = "Centrifuge" },
			[14] = { ["object"] = "v_med_cooler", ["price"] = 750, ["label"] = "Cooler" },
			[15] = { ["object"] = "v_med_cor_ceilingmonitor", ["price"] = 750, ["label"] = "Monitor" },
			[16] = { ["object"] = "v_med_cor_autopsytbl", ["price"] = 750, ["label"] = "Autopsy Table" },
			[17] = { ["object"] = "v_med_cor_cembin", ["price"] = 750, ["label"] = "Bin" },
			[18] = { ["object"] = "v_med_cor_cemtrolly2", ["price"] = 750, ["label"] = "Trolley" },
			[19] = { ["object"] = "v_med_cor_chemical", ["price"] = 750, ["label"] = "Chem" },
			[20] = { ["object"] = "v_med_cor_emblmtable", ["price"] = 750, ["label"] = "BLM Table" },
			[21] = { ["object"] = "v_med_cor_fileboxa", ["price"] = 750, ["label"] = "File Box" },
			[22] = { ["object"] = "v_med_cor_filingcab", ["price"] = 750, ["label"] = "File Cab" },
			[23] = { ["object"] = "v_med_cor_hose", ["price"] = 750, ["label"] = "Hose" },
			[24] = { ["object"] = "v_med_cor_largecupboard", ["price"] = 750, ["label"] = "Large Cupboard" },
			[25] = { ["object"] = "v_med_cor_lightbox", ["price"] = 750, ["label"] = "Lightbox" },
			[26] = { ["object"] = "v_med_cor_medstool", ["price"] = 750, ["label"] = "Medstool" },
			[27] = { ["object"] = "v_med_cor_minifridge", ["price"] = 750, ["label"] = "Minifridge" },
			[28] = { ["object"] = "v_med_cor_papertowels", ["price"] = 750, ["label"] = "Papertowels" },
			[29] = { ["object"] = "v_med_cor_photocopy", ["price"] = 750, ["label"] = "Photocopy" },
			[30] = { ["object"] = "v_med_cor_tvstand", ["price"] = 750, ["label"] = "TV Stand" },
			[31] = { ["object"] = "v_med_cor_wallunita", ["price"] = 750, ["label"] = "Wall Unit" },
			[32] = { ["object"] = "v_med_examlight", ["price"] = 750, ["label"] = "Exam Light" },
			[33] = { ["object"] = "v_med_gastank", ["price"] = 750, ["label"] = "Gas Tank" },
			[34] = { ["object"] = "v_med_hazmatscan", ["price"] = 750, ["label"] = "Hazmat Scan" },
			[35] = { ["object"] = "v_med_hospheadwall1", ["price"] = 750, ["label"] = "Head Wall" },
			[36] = { ["object"] = "v_med_hospseating1", ["price"] = 750, ["label"] = "Seating" },
			[37] = { ["object"] = "v_med_hosptable", ["price"] = 750, ["label"] = "Hosp Table" },
			[38] = { ["object"] = "v_med_latexgloveboxblue", ["price"] = 50, ["label"] = "Glove Box" },
			[39] = { ["object"] = "v_med_medwastebin", ["price"] = 750, ["label"] = "Wastebin" },
			[40] = { ["object"] = "v_med_oscillator3", ["price"] = 750, ["label"] = "Oscillator" },
			[41] = { ["object"] = "prop_ld_health_pack", ["price"] = 100, ["label"] = "Health Pack" }
		},
	},
	["walldecoration"] = {
		label = "Wall Decoration",
		items = {
			[1] = { ["object"] = "apa_p_h_acc_artwalll_02", ["price"] = 1000, ["label"] = "Painting with Surfaces" },
			[2] = { ["object"] = "v_ind_cs_toolboard", ["price"] = 500, ["label"] = "Tools" },
			[3] = { ["object"] = "apa_mp_stilts_bed_art", ["price"] = 300, ["label"] = "3D Art" },
			[4] = { ["object"] = "ex_office_swag_paintings03", ["price"] = 1000, ["label"] = "Ground Paintings" },
			[5] = { ["object"] = "ex_mp_h_acc_artwallm_03", ["price"] = 750, ["label"] = "Abstract Painting" },
			[6] = { ["object"] = "ex_p_h_acc_artwallm_04", ["price"] = 750, ["label"] = "Abstract Painting 2" },
			[7] = { ["object"] = "ex_p_h_acc_artwalll_01", ["price"] = 1250, ["label"] = "Abstract Painting groot" },
			[8] = { ["object"] = "apa_p_h_acc_artwalll_03", ["price"] = 750, ["label"] = "Abstract Painting 3" },
			[9] = { ["object"] = "ex_mp_h_acc_artwallm_02", ["price"] = 750, ["label"] = "Abstract Painting 4" },
			[10] = { ["object"] = "ex_p_h_acc_artwallm_03", ["price"] = 750, ["label"] = "Abstract Painting 5" },
			[11] = { ["object"] = "apa_mp_stilts_a_study_pics", ["price"] = 500, ["label"] = "Paintings" },
			[12] = { ["object"] = "apa_mp_h_acc_artwallm_02", ["price"] = 750, ["label"] = "Abstract Painting 6" },
			[13] = { ["object"] = "apa_mp_h_acc_artwalll_02", ["price"] = 750, ["label"] = "Abstract Painting 7" },
			[14] = { ["object"] = "apa_mp_h_acc_artwallm_04", ["price"] = 750, ["label"] = "Abstract Painting 8" },
			[15] = { ["object"] = "prop_dart_bd_cab_01", ["price"] = 250, ["label"] = "Dartboard" },
			[16] = { ["object"] = "prop_dart_bd_01", ["price"] = 250, ["label"] = "Dartboard 2" },
			[17] = { ["object"] = "vw_prop_vw_key_cabinet_01a", ["price"] = 250, ["label"] = "Key Box" }
		},
	},
}