Config = {}

Config.TestDriveTimer = 1000 * 60 * 2 -- 2m

Config.Locations = {
    ["boss"] = { ['x'] = -31.66366, ['y'] = -1113.505, ['z'] = 26.422349, ['h'] = 85.276741 },
    ["stash"] = { ['x'] = -27.65945, ['y'] = -1104.104, ['z'] = 26.422348, ['h'] = 250.80944 },
 }

Config.CarSpawns = {
	[1] =  { ['x'] = -38.25,['y'] = -1104.18,['z'] = 26.43,['h'] = 14.46, ['info'] = ' Car Spot 1' },
	[2] =  { ['x'] = -36.36,['y'] = -1097.3,['z'] = 26.43,['h'] = 109.4, ['info'] = ' Car Spot 2' },
	[3] =  { ['x'] = -43.11,['y'] = -1095.02,['z'] = 26.43,['h'] = 67.77, ['info'] = ' Car Spot 3' },
	[4] =  { ['x'] = -50.45,['y'] = -1092.66,['z'] = 26.43,['h'] = 116.33, ['info'] = ' Car Spot 4' },
}

Config.CarTable = {
	[1] = {name = "Hakuchou", costs = 22000, model = "hakuchou"}, 
	[2] = {name = "Windsor Drop", costs = 45000, model = "windsor2"},
	[3] = {name = "Specter", costs = 120000, model = "specter"},
	[4] = {name = "Brawler", costs = 99500, model = "brawler"},
}

Config.Menu = {
    x = 0.14,
    y = 0.15,
    width = 0.12,
    height = 0.03,
    buttons = 10,
    from = 1,
    to = 10,
    scale = 0.29,
    font = 0,
    ["main"] = {
        title = "CATEGORIES",
        name = "main",
        buttons = {
            {name = "Vehicles", description = ""},
            {name = "Motorcycles", description = ""},
            {name = "Cycles", description = ""},
        }
    },
    ["vehicles"] = {
        title = "VEHICLES",
        name = "vehicles",
        buttons = {
            {name = "Job Vehicles", description = ''},
            {name = "Compacts", description = ''},
            {name = "Coupes", description = ''},
            {name = "Sedans", description = ''},
            {name = "Sports", description = ''},
            {name = "Sports Classics", description = ''},
            {name = "Imports", description = ''},
            {name = "Muscle", description = ''},
            {name = "Off-Road", description = ''},
            {name = "SUVs", description = ''},
            {name = "Vans", description = ''},
        }
    },
    ["jobvehicles"] = {
        title = "job vehicles",
        name = "job vehicles",
        buttons = {
            {name = "Taxi Cab", costs = 4000, description = {}, model = "taxi"},
            {name = "Flat Bed", costs = 4000, description = {}, model = "flatbed"},
            {name = "News Rumpo", costs = 4000, description = {}, model = "rumpo"},
        }
    },
    ["compacts"] = {
        title = "compacts",
        name = "compacts",
        buttons = {			
            {name = "Blista", costs = 12000, description = {}, model = "blista"},
            {name = "Brioso R/A", costs = 22000, description = {}, model = "brioso"},
            {name = "Dilettante", costs = 10000, description = {}, model = "Dilettante"},
            {name = "Issi", costs = 14000, description = {}, model = "issi2"},
            {name = "Panto", costs = 8000, description = {}, model = "panto"},
            {name = "Prairie", costs = 9000, description = {}, model = "prairie"},
            {name = "Rhapsody", costs = 16000, description = {}, model = "rhapsody"},

        }
    },
    ["coupes"] = {
        title = "coupes",
        name = "coupes",
        buttons = {
            {name = "Cognoscenti Cabrio", costs = 150000, description = {}, model = "cogcabrio"},
            {name = "Exemplar", costs = 80000, description = {}, model = "exemplar"},
            {name = "F620", costs = 90000, description = {}, model = "f620"},
            {name = "Felon", costs = 50000, description = {}, model = "felon"},
            {name = "Felon GT", costs = 70000, description = {}, model = "felon2"},
            {name = "Jackal", costs = 40000, description = {}, model = "jackal"},
            {name = "Oracle", costs = 30000, description = {}, model = "oracle"},
            {name = "Oracle XS", costs = 35000, description = {}, model = "oracle2"},
            {name = "Sentinel", costs = 20000, description = {}, model = "sentinel"},
            {name = "Sentinel XS", costs = 25000, description = {}, model = "sentinel2"},
            {name = "Windsor", costs = 160000, description = {}, model = "windsor"},
            {name = "Windsor Drop", costs = 165000, description = {}, model = "windsor2"},
            {name = "Zion", costs = 10000, description = {}, model = "zion"},
            {name = "Zion Cabrio", costs = 15000, description = {}, model = "zion2"},
        }
    },
    ["sports"] = {
        title = "sports",
        name = "sports",
        buttons = {
            {name = "9F", costs = 200000, description = {}, model = "ninef"},
            {name = "9F Cabrio", costs = 250000, description = {}, model = "ninef2"},
            {name = "Alpha", costs = 15000, description = {}, model = "alpha"},
            {name = "Banshee", costs = 150000, description = {}, model = "banshee"},
            {name = "Bestia GTS", costs = 175000, description = {}, model = "bestiagts"},
            {name = "Buffalo", costs = 15000, description = {}, model = "buffalo"},
            {name = "Buffalo S", costs = 20000, description = {}, model = "buffalo2"},
            {name = "Carbonizzare", costs = 250000, description = {}, model = "carbonizzare"},
            {name = "Comet", costs = 215000, description = {}, model = "comet2"},
            {name = "Coquette", costs = 135000, description = {}, model = "coquette"},
            {name = "Feltzer", costs = 75000, description = {}, model = "feltzer2"},
            {name = "Furore GT", costs = 30000, description = {}, model = "furoregt"},
            {name = "Fusilade", costs = 15000, description = {}, model = "fusilade"},
            {name = "Jester", costs = 275000, description = {}, model = "jester"},
            {name = "Kuruma", costs = 110000, description = {}, model = "kuruma"},
            {name = "Lynx", costs = 125000, description = {}, model = "lynx"},
            {name = "Massacro", costs = 200000, description = {}, model = "massacro"},
            {name = "Omnis", costs = 150000, description = {}, model = "omnis"},
            {name = "Penumbra", costs = 15000, description = {}, model = "penumbra"},
            {name = "Rapid GT", costs = 40000, description = {}, model = "rapidgt"},
            {name = "Rapid GT Convertible", costs = 60000, description = {}, model = "rapidgt2"},
            {name = "Schafter V12", costs = 50000, description = {}, model = "schafter3"},
            {name = "Sultan", costs = 65000, description = {}, model = "sultan"},
            {name = "Surano", costs = 125000, description = {}, model = "surano"},
            {name = "Tropos", costs = 325000, description = {}, model = "tropos"},
            {name = "Verkierer", costs = 225000, description = {}, model = "verlierer2"},
            {name = "Comet SR", costs = 275000, description = {}, model = "comet5"},
            {name = "Sentinel Classic", costs = 125000, description = {}, model = "sentinel3"},
            {name = "Streiter", costs = 75000, description = {}, model = "streiter"},
            {name = "Comet Safari", costs = 250000, description = {}, model = "comet4"},
            {name = "Pariah", costs = 75000, description = {}, model = "pariah"},
            {name = "Elegy", costs = 175000, description = {}, model = "elegy2"},
        }
    },
    ["sportsclassics"] = {
        title = "sports classics",
        name = "sportsclassics",
        buttons = {
            {name = "Casco", costs = 250000, description = {}, model = "casco"},
            {name = "Coquette Classic", costs = 60000, description = {}, model = "coquette2"},
            {name = "JB 700", costs = 55000, description = {}, model = "jb700"},
            {name = "Pigalle", costs = 10000, description = {}, model = "pigalle"},
            {name = "Stinger", costs = 200000, description = {}, model = "stinger"},
            {name = "Stinger GT", costs = 235000, description = {}, model = "stingergt"},
            {name = "Stirling GT", costs = 100000, description = {}, model = "feltzer3"},
            {name = "Rapid GT Classic", costs = 45000, description = {}, model = "rapidgt3"},
            {name = "Retinue", costs = 130000, description = {}, model = "retinue"},
            {name = "Viseris", costs = 128000, description = {}, model = "viseris"}, 
            {name = "190z", costs = 115000, description = {}, model = "z190"},
            {name = "GT500", costs = 140000, description = {}, model = "gt500"},
            {name = "Savestra", costs = 125000, description = {}, model = "savestra"},
            {name = "Elegy Retro Custom", costs = 250000, description = {}, model = "elegy"},
        }
    },
    ["imports"] = {
        title = "imports",
        name = "imports",
        buttons = {
             --[[ {name = "Audi RS7", costs = 125000, description = {}, model = "rs7"},
             {name = "Audi R8 V10", costs = 425000, description = {}, model = "r8v10"},
             {name = "Audi R8 Liberty Walk", costs = 595000, description = {}, model = "ar8lb"},
             {name = "AMG GTR", costs = 400000, description = {}, model = "gtrc"},
             {name = "Audi RS6", costs = 350000, description = {}, model = "audirs6tk"},
             {name = "BMW E36", costs = 225000, description = {}, model = "e36prb"},
             {name = "BMW E46", costs = 350000, description = {}, model = "e46"},
             {name = "BMW I8", costs = 325000, description = {}, model = "acs8"},
             {name = "BMW E60", costs = 325000, description = {}, model = "m5e60"},
             {name = "BMW M3 E46", costs = 390000, description = {}, model = "m3e46"},
             {name = "BMW M4", costs = 400000, description = {}, model = "m4"},
             {name = "Bentley Continental", costs = 290000, description = {}, model = "contss18"},
             {name = "Bentley Dragon", costs = 325000, description = {}, model = "bdragon"},
             {name = "CorvetteC7", costs = 345000, description = {}, model = "c7"},
             {name = "Charger 69", costs = 325000, description = {}, model = "69charger"},
             {name = "Camaro Exorcist", costs = 325000, description = {}, model = "exor"},
             {name = "Camaro Z28", costs = 265000, description = {}, model = "z2879"},
             {name = "Camaro ZL1", costs = 375000, description = {}, model = "czl1"},
             {name = "Comet 6STR", costs = 200000, description = {}, model = "comet6str"},
             {name = "Del Sol EG", costs = 50000, description = {}, model = "delsoleg"},
             {name = "Datsun 510", costs = 330000, description = {}, model = "510"},
             {name = "Escalade", costs = 350000, description = {}, model = "esv"},
             {name = "Ellie 6STR", costs = 475000, description = {}, model = "ellie6str"},
             {name = "Ford Mustang 66", costs = 275000, description = {}, model = "66fastback"},
             {name = "Ford Mustang 2019", costs = 250000, description = {}, model = "mustang19"},
             {name = "Ford Mustang WideBody", costs = 325000, description = {}, model = "rmodmustang"},
             {name = "Ford Focus RS", costs = 300000, description = {}, model = "focusrs"},
             {name = "Ford F150", costs = 200000, description = {}, model = "f150"},
             {name = "Ferrari Enzo", costs = 457000, description = {}, model = "mig"},
             {name = "Ferrari LaFerrari", costs = 485000, description = {}, model = "laferrari17"},
             {name = "Futo 6STR", costs = 200000, description = {}, model = "futo2"},
             {name = "Gauntlet 6STR", costs = 225000, description = {}, model = "gauntlet6str"},
             {name = "Harley", costs = 95500, description = {}, model = "rudiharley"},
             {name = "Honda NSX", costs = 135000, description = {}, model = "na1"},
             {name = "Honda S2000", costs = 150000, description = {}, model = "ap2"},
             {name = "Honda Integra", costs = 150000, description = {}, model = "dc5"},
             {name = "Honda NSX 2016", costs = 300000, description = {}, model = "filthynsx"},
             {name = "Honda Civic TypeR", costs = 275000, description = {}, model = "fk8"},
             {name = "HoldenSV", costs = 125000, description = {}, model = "bluecunt"},
             {name = "Hellion V2", costs = 190000, description = {}, model = "hellion6str"},
             {name = "Jeep Grand Cheroke", costs = 329000, description = {}, model = "srt8b"},
             {name = "Kawasaki ZX10", costs = 120000, description = {}, model = "zx10"},
             {name = "Lamborghini Aventador", costs = 475000, description = {}, model = "lp700r"},
             {name = "Lamborghini Diablo", costs = 300000, description = {}, model = "500gtrlam"},
             {name = "Lamborghini Murcielago", costs = 295000, description = {}, model = "lp670"},
             {name = "Lamborghini Murcielago WideBody", costs = 355000, description = {}, model = "lwlp670"},
             {name = "Lexus RCF", costs = 325000, description = {}, model = "rcf"},
             {name = "LadyBird 6STR", costs = 475000, description = {}, model = "ladybird6str"},
             {name = "Mazda RocketBunny RX7", costs = 175000, description = {}, model = "rx7rb"},
             {name = "Mazda RX7", costs = 75000, description = {}, model = "fnfrx7"},
             {name = "Mazda RX7 FC", costs = 195000, description = {}, model = "fc3s"},
             {name = "Mazda Miata", costs = 150000, description = {}, model = "na6"},
             {name = "McLaren P1", costs = 800000, description = {}, model = "p1"},
             {name = "McLaren 650", costs = 625000, description = {}, model = "650slw"},
             {name = "Maserati Gran Turismo", costs = 395000, description = {}, model = "granlb"},
             {name = "Mitsubishi Evo6", costs = 325000, description = {}, model = "cp9a"},
             {name = "Mitsubishi Evo9", costs = 245000, description = {}, model = "evo9"},
             {name = "Mitsubishi Evo10", costs = 135000, description = {}, model = "evo10"},
             {name = "Mitsubishi Eclipse", costs = 125000, description = {}, model = "eclipse"},
             {name = "Mercedes C63 AMG", costs = 290000, description = {}, model = "c63"},
             {name = "Mercedes G65 AMG", costs = 125000, description = {}, model = "g65amg"},
             {name = "Mercedes GT63", costs = 390000, description = {}, model = "gt63"},
             {name = "Mercedes 124", costs = 325000, description = {}, model = "mbw124"},
             {name = "Nissan LibertyWalk GTR", costs = 700000, description = {}, model = "lwgtr"},
             {name = "Nissan LibertyWalk GTR 2", costs = 500000, description = {}, model = "lwgtr2"},
             {name = "Nissan RHD GTR", costs = 328000, description = {}, model = "r35"},
             {name = "Nissan GTR", costs = 325000, description = {}, model = "gtr"},
             {name = "Nissan S13", costs = 255000, description = {}, model = "nis13"},
             {name = "Nissan R34 4 Door", costs = 227000, description = {}, model = "er34"},
             {name = "Nissan R34", costs = 200000, description = {}, model = "fnf4r34"},
             {name = "Nissan S15", costs = 350000, description = {}, model = "s15rb"},
             {name = "Nissan 300zw", costs = 425000, description = {}, model = "300zw"},
             {name = "Nissan 300zx", costs = 165000, description = {}, model = "z32"},
             {name = "Nissan 370z", costs = 250000, description = {}, model = "370z"},
             {name = "Porsche 911", costs = 375000, description = {}, model = "por930"},
             {name = "Porsche 911 Turbo S", costs = 325000, description = {}, model = "911turbos"},
             {name = "Porsche 911 Rocket Bunny", costs = 245000, description = {}, model = "911rwb"},
             {name = "Porsche 911 Rocket Bunny 2", costs = 255000, description = {}, model = "gt2rwb"},
             {name = "Porsche GT3 RS", costs = 380000, description = {}, model = "gt3rs"},
             {name = "Porsche Panamera", costs = 400000, description = {}, model = "panamera17turbo"},
             {name = "Porsche 918 Spyder", costs = 375000, description = {}, model = "918"},
             {name = "Pagani Zonda R", costs = 497000, description = {}, model = "zondar"},
             {name = "Ruiner 6STR", costs = 235000, description = {}, model = "ruiner6str"},
             --{name = "Regera", costs = 0000000, description = {}, model = "regera"},
             {name = "Rolls Royce Wraith", costs = 425000, description = {}, model = "wraith"},
             {name = "Subaru STI WRX", costs = 125000, description = {}, model = "subwrx"},
             {name = "Subaru WRX", costs = 95000, description = {}, model = "ff4wrx"},
             {name = "Sentinel 6STR", costs = 200000, description = {}, model = "sentinel6str"},
             {name = "Sentinel 6STR 2", costs = 350000, description = {}, model = "sentinel6str2"},
             {name = "Schwartzer 6STR ", costs = 225000, description = {}, model = "schwarzer2"},
             {name = "Stratum 6STR", costs = 210500, description = {}, model = "stratumc"},
             {name = "Sultan RS MK2", costs = 245000, description = {}, model = "sultanrsv8"},
             {name = "Tempesta 6STR", costs = 490000, description = {}, model = "tempesta2"},
             {name = "Toyota Supra", costs = 345000, description = {}, model = "a80"},
             {name = "Tampa V3", costs = 210000, description = {}, model = "tampa5"},
             {name = "Volkswagen Golf", costs = 150000, description = {}, model = "golfp"},
             {name = "Yamaha R1", costs = 125000, description = {}, model = "r1"},
             {name = "Yosemite 6STR", costs = 195000, description = {}, model = "yosemite6str"},
             {name = "ZR380", costs = 145000, description = {}, model = "zr3806str"}, ]]		 		
        }
    },
    ["casino"] = {
        title = "casino",
        name = "casino",
        buttons = {
--				{name = "Jugular", costs = 175000, description = {}, model = "jugular"},
--				{name = "Peyote", costs = 75000, description = {}, model = "peyote2"},
--				{name = "Gauntlet 4", costs = 150000, description = {}, model = "gauntlet4"},
--				{name = "Caracara", costs = 190000, description = {}, model = "caracara2"},
--				{name = "Novak", costs = 140000, description = {}, model = "Novak"},
--				{name = "Issi 7", costs = 200000, description = {}, model = "issi7"},
--				{name = "Hellion", costs = 110000, description = {}, model = "hellion"},
--				{name = "Dynasty", costs = 110000, description = {}, model = "Dynasty"},
--				{name = "Gauntlet 3", costs = 130000, description = {}, model = "gauntlet3"},
--				{name = "Nebula", costs = 83000, description = {}, model = "nebula"},
--				{name = "Zion 3", costs = 75000, description = {}, model = "zion3"},
--				{name = "Drafter", costs = 140000, description = {}, model = "drafter"},
--				{name = "Komoda", costs = 195000, description = {}, model = "komoda"},
--				{name = "Rebla", costs = 110000, description = {}, model = "rebla"},
--				{name = "Retinue", costs = 80000, description = {}, model = "retinue2"},
--				{name = "Sugoi", costs = 105000, description = {}, model = "sugoi"},
--				{name = "Sultan 2", costs = 155000, description = {}, model = "sultan2"},
--				{name = "VSTR", costs = 186000, description = {}, model = "vstr"},
        }
    },
    
    ["muscle"] = {
        title = "muscle",
        name = "muscle",
        buttons = {
            {name = "Blade", costs = 22000, description = {}, model = "blade"},
            {name = "Buccaneer", costs = 24000, description = {}, model = "buccaneer"},
            {name = "Chino", costs = 26000, description = {}, model = "chino"},
            {name = "Coquette BlackFin", costs = 115000, description = {}, model = "coquette3"},
            {name = "Dominator", costs = 40000, description = {}, model = "dominator"},
            {name = "Dukes", costs = 45000, description = {}, model = "dukes"},
            {name = "Gauntlet", costs = 36000, description = {}, model = "gauntlet"},
            {name = "Faction", costs = 36000, description = {}, model = "faction"},
            {name = "Picador", costs = 10000, description = {}, model = "picador"},
            {name = "Sabre Turbo", costs = 24000, description = {}, model = "sabregt"},
            {name = "Tampa", costs = 34000, description = {}, model = "tampa"},
            {name = "Virgo", costs = 22000, description = {}, model = "virgo"},
            {name = "Vigero", costs = 23000, description = {}, model = "vigero"},
            {name = "Elliie", costs = 290000, description = {}, model = "ellie"},
            {name = "Phoenix", costs = 34000, description = {}, model = "phoenix"},
            {name = "Slam Van", costs = 35000, description = {}, model = "slamvan"},
            {name = "Yosemite", costs = 45000, description = {}, model = "yosemite"},
            {name = "Tulip", costs = 55000, description = {}, model = "tulip"},
            {name = "Vamos", costs = 65000, description = {}, model = "vamos"},
        }
    },
    ["offroad"] = {
        title = "off-road",
        name = "off-road",
        buttons = {
            {name = "Bifta", costs = 15000, description = {}, model = "bifta"},
            {name = "Blazer", costs = 7000, description = {}, model = "blazer"},
            {name = "Brawler", costs = 40000, description = {}, model = "brawler"},
            {name = "Dune Buggy", costs = 10000, description = {}, model = "dune"},
            {name = "Rebel", costs = 45000, description = {}, model = "rebel2"},
            {name = "Sandking", costs = 70000, description = {}, model = "sandking"},
            {name = "Kamacho", costs = 90000, description = {}, model = "kamacho"},
            {name = "Dubsta 6x6", costs = 95000, description = {}, model = "dubsta3"},
        }
    },
    ["suvs"] = {
        title = "suvs",
        name = "suvs",
        buttons = {
            {name = "Cavalcade", costs = 30000, description = {}, model = "cavalcade2"},
            {name = "Granger", costs = 26000, description = {}, model = "granger"},
            {name = "Huntley S", costs = 225000, description = {}, model = "huntley"},
            {name = "Landstalker", costs = 40000, description = {}, model = "landstalker"},
            {name = "Radius", costs = 16000, description = {}, model = "radi"},
            {name = "Rocoto", costs = 24000, description = {}, model = "rocoto"},
            {name = "Seminole", costs = 10500, description = {}, model = "seminole"},
            {name = "XLS", costs = 110000, description = {}, model = "xls"},
            {name = "Dubsta", costs = 60000, description = {}, model = "dubsta"},
            {name = "Patriot", costs = 40000, description = {}, model = "patriot"},
            {name = "Gresley", costs = 25000, description = {}, model = "gresley"},
            {name = "Toros", costs = 110000, description = {}, model = "toros"},
        }
    },
    ["vans"] = {
        title = "vans",
        name = "vans",
        buttons = {
            {name = "Bison", costs = 30000, description = {}, model = "bison"},
            {name = "Bobcat XL", costs = 15000, description = {}, model = "bobcatxl"},
            {name = "Gang Burrito", costs = 15000, description = {}, model = "gburrito"},
            {name = "Journey", costs = 10000, description = {}, model = "journey"},
            {name = "Minivan", costs = 65000, description = {}, model = "minivan"},
            {name = "Paradise", costs = 22000, description = {}, model = "paradise"},
            {name = "Surfer", costs = 9500, description = {}, model = "surfer"},
            {name = "Youga", costs = 14500, description = {}, model = "youga"},
            {name = "Moonbeam", costs = 12500, description = {}, model = "moonbeam"},
            {name = "Camper", costs = 34500, description = {}, model = "camper"},
        }
    },
    ["sedans"] = {
        title = "sedans",
        name = "sedans",
        buttons = {
            {name = "Emperor", costs = 7000, description = {}, model = "emperor2"},
            {name = "Tornado", costs = 9000, description = {}, model = "tornado3"},
            {name = "Bodhi", costs = 5000, description = {}, model = "bodhi2"},		
            {name = "Asea", costs = 9500, description = {}, model = "asea"},
            {name = "Asterope", costs = 10000, description = {}, model = "asterope"},
            {name = "Fugitive", costs = 30000, description = {}, model = "fugitive"},
            {name = "Glendale", costs = 7500, description = {}, model = "glendale"},
            {name = "Intruder", costs = 25000, description = {}, model = "intruder"},
            {name = "Premier", costs = 9000, description = {}, model = "premier"},
            {name = "Regina", costs = 32000, description = {}, model = "regina"},
            {name = "Schafter", costs = 45000, description = {}, model = "schafter2"},
            {name = "Stanier", costs = 10000, description = {}, model = "stanier"},
            {name = "Stratum", costs =90000, description = {}, model = "stratum"},
            {name = "Super Diamond", costs = 50000, description = {}, model = "superd"},
            {name = "Warrener", costs = 85000, description = {}, model = "warrener"},
            {name = "Washington", costs = 18000, description = {}, model = "washington"},
            {name = "Tailgater", costs = 87500, description = {}, model = "tailgater"},
            {name = "Cognoscenti", costs = 30000, description = {}, model = "cognoscenti"},
        }
    },
    ["motorcycles"] = {
        title = "MOTORCYCLES",
        name = "motorcycles",
        buttons = {		
            {name = "Akuma", costs = 70000, description = {}, model = "AKUMA"},
            {name = "Bagger", costs = 50000, description = {}, model = "bagger"},
            {name = "Bati 801", costs = 45000, description = {}, model = "bati"},
            {name = "BF400", costs = 72000, description = {}, model = "bf400"},
            {name = "Carbon RS", costs = 55000, description = {}, model = "carbonrs"},
            {name = "Daemon", costs = 25000, description = {}, model = "daemon"},
            {name = "Enduro", costs = 55000, description = {}, model = "enduro"},
            {name = "Faggio", costs = 15000, description = {}, model = "faggio"},
            {name = "Gargoyle", costs = 35000, description = {}, model = "gargoyle"},
            {name = "Hexer", costs = 45000, description = {}, model = "hexer"},
            {name = "Innovation", costs = 75000, description = {}, model = "innovation"},
            {name = "Nemesis", costs = 50000, description = {}, model = "nemesis"},
            {name = "PCJ-600", costs = 55000, description = {}, model = "pcj"},
            {name = "Ruffian", costs = 54000, description = {}, model = "ruffian"},
            {name = "Sanchez", costs = 65000, description = {}, model = "sanchez"},
            {name = "Sovereign", costs = 59000, description = {}, model = "sovereign"},
            {name = "Zombiea", costs = 65000, description = {}, model = "zombiea"},
            {name = "Vespa", costs = 15000, description = {}, model = "faggio2"},
            {name = "Manchez", costs = 67000, description = {}, model = "manchez"},
            {name = "Vortex", costs = 80000, description = {}, model = "vortex"},
            {name = "Avarus", costs = 55000, description = {}, model = "avarus"},
            {name = "Vader", costs = 75000, description = {}, model = "vader"},
            {name = "Esskey", costs = 65000, description = {}, model = "esskey"},
            {name = "Defiler", costs = 85000, description = {}, model = "defiler"},
            {name = "Chimera", costs = 65000, description = {}, model = "chimera"},
            {name = "Daemon", costs = 75000, description = {}, model = "daemon"},
            {name = "DaemonHigh", costs = 65000, description = {}, model = "daemon2"},
        }
    },
    ["cycles"] = {
        title = "cycles",
        name = "cycles",
        buttons = {
            {name = "BMX", costs = 550, description = {}, model = "bmx"},
            {name = "Cruiser", costs = 240, description = {}, model = "cruiser"},
            {name = "Fixter", costs = 270, description = {}, model = "fixter"},
            {name = "Scorcher", costs = 300, description = {}, model = "scorcher"},
            {name = "Pro 1", costs = 2500, description = {}, model = "tribike"},
            {name = "Pro 2", costs = 2600, description = {}, model = "tribike2"},
            {name = "Pro 3", costs = 2900, description = {}, model = "tribike3"},
        }
    },
}