Config = {}

Config.AttachmentCrafting = {
    ["location"] = {x = 896.44866, y = -3217.424, z = -98.22556, h = 58.780258, r = 1.0}, 
    ["items"] = {
        [1] = {
            name = "pistol_extendedclip",
            amount = 10,
            info = {},
            costs = {
                ["metalscrap"] = 30,
                ["steel"] = 30,
                ["rubber"] = 30,
            },
            type = "item",
            slot = 1,
            threshold = 0,
            points = 0,
        },
        [2] = {
            name = "pistol_suppressor",
            amount = 10,
            info = {},
            costs = {
                ["metalscrap"] = 30,
                ["steel"] = 30,
                ["rubber"] = 30,
            },
            type = "item",
            slot = 2,
            threshold = 0,
            points = 0,
        },
        [3] = {
            name = "rifle_extendedclip",
            amount = 10,
            info = {},
            costs = {
                ["metalscrap"] = 50,
                ["steel"] = 50,
                ["rubber"] = 50,
                ["smg_extendedclip"] = 1,
            },
            type = "item",
            slot = 7,
            threshold = 0,
            points = 0,
        },
        [4] = {
            name = "rifle_drummag",
            amount = 10,
            info = {},
            costs = {
                ["metalscrap"] = 60,
                ["steel"] = 60,
                ["rubber"] = 60,
                ["rifle_extendedclip"] = 1,
            },
            type = "item",
            slot = 8,
            threshold = 0,
            points = 0,
        },
        [5] = {
            name = "smg_flashlight",
            amount = 10,
            info = {},
            costs = {
                ["metalscrap"] = 40,
                ["steel"] = 40,
                ["rubber"] = 40,
            },
            type = "item",
            slot = 3,
            threshold = 0,
            points = 0,
        },
        [6] = {
            name = "smg_extendedclip",
            amount = 10,
            info = {},
            costs = {
                ["metalscrap"] = 40,
                ["steel"] = 40,
                ["rubber"] = 40,
            },
            type = "item",
            slot = 4,
            threshold = 0,
            points = 0,
        },
        [7] = {
            name = "smg_suppressor",
            amount = 10,
            info = {},
            costs = {
                ["metalscrap"] = 40,
                ["steel"] = 40,
                ["rubber"] = 40,
            },
            type = "item",
            slot = 5,
            threshold = 0,
            points = 0,
        },
        [8] = {
            name = "smg_scope",
            amount = 10,
            info = {},
            costs = {
                ["metalscrap"] = 40,
                ["steel"] = 40,
                ["rubber"] = 40,
            },
            type = "item",
            slot = 6,
            threshold = 0,
            points = 0,
        },
    }
}

Config.CraftingItems = {
    [1] = {
        name = "screwdriverset",
        amount = 50,
        info = {},
        costs = {
            ["metalscrap"] = 50,
            ["plastic"] = 40,
        },
        type = "item",
        slot = 1,
        threshold = 0,
        points = 0,
    },
    [2] = {
        name = "advancedscrewdriver",
        amount = 50,
        info = {},
        costs = {
            ["metalscrap"] = 90,
            ["plastic"] = 70,
        },
        type = "item",
        slot = 2,
        threshold = 0,
        points = 0,
    },
    [3] = {
        name = "electronickit",
        amount = 50,
        info = {},
        costs = {
            ["metalscrap"] = 140,
            ["plastic"] = 140,
            ["aluminum"] = 140,
        },
        type = "item",
        slot = 3,
        threshold = 0,
        points = 0,
    },
    [4] = {
        name = "radioscanner",
        amount = 50,
        info = {},
        costs = {
            ["electronickit"] = 1,
            ["plastic"] = 50,
            ["steel"] = 50,
        },
        type = "item",
        slot = 4,
        threshold = 0,
        points = 0,
    },
    [5] = {
        name = "gatecrack",
        amount = 50,
        info = {},
        costs = {
            ["metalscrap"] = 75,
            ["plastic"] = 100,
            ["aluminum"] = 120,
            ["iron"] = 50,
            ["electronickit"] = 2,
        },
        type = "item",
        slot = 5,
        threshold = 0,
        points = 0,
    },
    [6] = {
        name = "handcuffs",
        amount = 50,
        info = {},
        costs = {
            ["steel"] = 50,
            ["aluminum"] = 30,
        },
        type = "item",
        slot = 6,
        threshold = 0,
        points = 0,
    },
    [7] = {
        name = "drill",
        amount = 50,
        info = {},
        costs = {
            ["iron"] = 200,
            ["steel"] = 200,
            ["screwdriverset"] = 2,
            ["advancedlockpick"] = 2,
        },
        type = "item",
        slot = 7,
        threshold = 0,
        points = 0,
    },
    [8] = {
        name = "advancedlockpick",
        amount = 50,
        info = {},
        costs = {
            ["iron"] = 50,
            ["steel"] = 10,
            ["lockpick"] = 1,
            ["glass"] = 150,
        },
        type = "item",
        slot = 8,
        threshold = 0,
        points = 0,
    },
    [9] = {
        name = "trojan_usb",
        amount = 50,
        info = {},
        costs = {
            ["glass"] = 50,
            ["steel"] = 125,
            ["copper"] = 125,
        },
        type = "item",
        slot = 9,
        threshold = 0,
        points = 0,
    },
    [10] = {
        name = "thermite",
        amount = 50,
        info = {},
        costs = {
            ["glass"] = 35,
            ["steel"] = 65,
            ["copper"] = 95,
        },
        type = "item",
        slot = 10,
        threshold = 0,
        points = 0,
    },
    [11] = {
        name = "lockpick",
        amount = 50,
        info = {},
        costs = {
            ["aluminum"] = 25,
            ["metalscrap"] = 25,
			["steel"] = 15,
        },
        type = "item",
        slot = 11,
        threshold = 0,
        points = 0,
    },
}

--[[ "metalscrap",
"plastic",
"copper",
"iron",
"aluminum",
"steel",
"glass", ]]