RLCustoms = RLCustoms or {}

RLCustoms.Locations = {
    [1] = {
        ["busy"] = false, 
        ['type'] = 'bennys',
        ["coords"] = {x = -1155.66, y = -2006.38, z = 13.18, h = 313.5, r = 1.0}, 
    },
    [2] = {
        ["busy"] = false, 
        ['type'] = 'bennys',
        ["coords"] = {x = -211.4, y = -1324.96, z = 30.89, h = 327.5, r = 1.0}, 
    }
}

RLCustoms.BlacklistedVehicles = {
    "ptouran",
    "ptouran",
    "ptouran11",
    "pbklasse",
    "paudi",
    "pamarok",
    "pt5",
    "pt6",
    "pfosprinter",
    "pyamahamotor",
    "pbmwmotor2",
    "pschafter",
    "poracle",
    "dsimerc",
    "dsivito",
    "dsiq5",
}

RLCustoms.Mods = {
    ["respray"] = {
        id = "respray",
        label = "Respray",
        buttons = { 
            [1] = {
                id = "respray",
                name = "Primary Color", 
                buttons = {
                    {
                        id = "respray",
                        name = "Chrome",  
                        buttons = {
                            {name = "Chrome", modid = 120, price = 1000, colortype = "primary", spraytype = "chrome", modtype = "respray"}
                        }
                    },
                    {
                        id = "respray",
                        name = "Classic",  
                        buttons = { 
                            {spraytype = "classic", name = "Black",            colortype = "primary", modtype = "respray", price = 500, modid = 0},
                            {spraytype = "classic", name = "Carbon Black",     colortype = "primary", modtype = "respray", price = 500, modid = 147},
                            {spraytype = "classic", name = "Hraphite",         colortype = "primary", modtype = "respray", price = 500, modid = 1},
                            {spraytype = "classic", name = "Anhracite Black",  colortype = "primary", modtype = "respray", price = 500, modid = 11},
                            {spraytype = "classic", name = "Black Steel",      colortype = "primary", modtype = "respray", price = 500, modid = 2},
                            {spraytype = "classic", name = "Dark Steel",       colortype = "primary", modtype = "respray", price = 500, modid = 3},
                            {spraytype = "classic", name = "Silver",           colortype = "primary", modtype = "respray", price = 500, modid = 4},
                            {spraytype = "classic", name = "Bluish Silver",    colortype = "primary", modtype = "respray", price = 500, modid = 5},
                            {spraytype = "classic", name = "Rolled Steel",     colortype = "primary", modtype = "respray", price = 500, modid = 6},
                            {spraytype = "classic", name = "Shadow Silver",    colortype = "primary", modtype = "respray", price = 500, modid = 7},
                            {spraytype = "classic", name = "Stone Silver",     colortype = "primary", modtype = "respray", price = 500, modid = 8},
                            {spraytype = "classic", name = "Midnight Silver",  colortype = "primary", modtype = "respray", price = 500, modid = 9},
                            {spraytype = "classic", name = "Cast Iron Silver", colortype = "primary", modtype = "respray", price = 500, modid = 10},
                            {spraytype = "classic", name = "Red",              colortype = "primary", modtype = "respray", price = 500, modid = 27},
                            {spraytype = "classic", name = "Torino Red",       colortype = "primary", modtype = "respray", price = 500, modid = 28},
                            {spraytype = "classic", name = "Formula Red",      colortype = "primary", modtype = "respray", price = 500, modid = 29},
                            {spraytype = "classic", name = "Lava Red",         colortype = "primary", modtype = "respray", price = 500, modid = 150},
                            {spraytype = "classic", name = "Blaze Red",        colortype = "primary", modtype = "respray", price = 500, modid = 30},
                            {spraytype = "classic", name = "Grace Red",        colortype = "primary", modtype = "respray", price = 500, modid = 31},
                            {spraytype = "classic", name = "Garnet Red",       colortype = "primary", modtype = "respray", price = 500, modid = 32},
                            {spraytype = "classic", name = "Sunset Red",       colortype = "primary", modtype = "respray", price = 500, modid = 33},
                            {spraytype = "classic", name = "Cabernet Red",     colortype = "primary", modtype = "respray", price = 500, modid = 34},
                            {spraytype = "classic", name = "Wine Red",         colortype = "primary", modtype = "respray", price = 500, modid = 143},
                            {spraytype = "classic", name = "Candy Red",        colortype = "primary", modtype = "respray", price = 500, modid = 35},
                            {spraytype = "classic", name = "Hot Pink",         colortype = "primary", modtype = "respray", price = 500, modid = 135},
                            {spraytype = "classic", name = "Pfsiter Pink",     colortype = "primary", modtype = "respray", price = 500, modid = 137},
                            {spraytype = "classic", name = "Salmon Pink",      colortype = "primary", modtype = "respray", price = 500, modid = 136},
                            {spraytype = "classic", name = "Sunrise Orange",   colortype = "primary", modtype = "respray", price = 500, modid = 36},
                            {spraytype = "classic", name = "Orange",           colortype = "primary", modtype = "respray", price = 500, modid = 38},
                            {spraytype = "classic", name = "Bright Orange",    colortype = "primary", modtype = "respray", price = 500, modid = 138},
                            {spraytype = "classic", name = "Gold",             colortype = "primary", modtype = "respray", price = 500, modid = 99},
                            {spraytype = "classic", name = "Bronze",           colortype = "primary", modtype = "respray", price = 500, modid = 90},
                            {spraytype = "classic", name = "Yellow",           colortype = "primary", modtype = "respray", price = 500, modid = 88},
                            {spraytype = "classic", name = "Race Yellow",      colortype = "primary", modtype = "respray", price = 500, modid = 89},
                            {spraytype = "classic", name = "Dew Yellow",       colortype = "primary", modtype = "respray", price = 500, modid = 91},
                            {spraytype = "classic", name = "Dark Green",       colortype = "primary", modtype = "respray", price = 500, modid = 49},
                            {spraytype = "classic", name = "Racing Green",     colortype = "primary", modtype = "respray", price = 500, modid = 50},
                            {spraytype = "classic", name = "Sea Green",        colortype = "primary", modtype = "respray", price = 500, modid = 51},
                            {spraytype = "classic", name = "Olive Green",      colortype = "primary", modtype = "respray", price = 500, modid = 52},
                            {spraytype = "classic", name = "Bright Green",     colortype = "primary", modtype = "respray", price = 500, modid = 53},
                            {spraytype = "classic", name = "Gasoline Green",   colortype = "primary", modtype = "respray", price = 500, modid = 54},
                            {spraytype = "classic", name = "Lime Green",       colortype = "primary", modtype = "respray", price = 500, modid = 92},
                            {spraytype = "classic", name = "Midnight Blue",    colortype = "primary", modtype = "respray", price = 500, modid = 141},
                            {spraytype = "classic", name = "Galaxy Blue",      colortype = "primary", modtype = "respray", price = 500, modid = 61},
                            {spraytype = "classic", name = "Dark Blue",        colortype = "primary", modtype = "respray", price = 500, modid = 62},
                            {spraytype = "classic", name = "Saxon Blue",       colortype = "primary", modtype = "respray", price = 500, modid = 63},
                            {spraytype = "classic", name = "Blue",             colortype = "primary", modtype = "respray", price = 500, modid = 64},
                            {spraytype = "classic", name = "Mariner Blue",     colortype = "primary", modtype = "respray", price = 500, modid = 65},
                            {spraytype = "classic", name = "Harbor Blue",      colortype = "primary", modtype = "respray", price = 500, modid = 66},
                            {spraytype = "classic", name = "Diamond Blue",     colortype = "primary", modtype = "respray", price = 500, modid = 67},
                            {spraytype = "classic", name = "Surf Blue",        colortype = "primary", modtype = "respray", price = 500, modid = 68},
                            {spraytype = "classic", name = "Nautical Blue",    colortype = "primary", modtype = "respray", price = 500, modid = 69},
                            {spraytype = "classic", name = "Racing Blue",      colortype = "primary", modtype = "respray", price = 500, modid = 73},
                            {spraytype = "classic", name = "Ultra Blue",       colortype = "primary", modtype = "respray", price = 500, modid = 70},
                            {spraytype = "classic", name = "Light Blue",       colortype = "primary", modtype = "respray", price = 500, modid = 74},
                            {spraytype = "classic", name = "Chocolate Brown",  colortype = "primary", modtype = "respray", price = 500, modid = 96},
                            {spraytype = "classic", name = "Bison Brown",      colortype = "primary", modtype = "respray", price = 500, modid = 101},
                            {spraytype = "classic", name = "Creeen Brown",     colortype = "primary", modtype = "respray", price = 500, modid = 95},
                            {spraytype = "classic", name = "Feltzer Brown",    colortype = "primary", modtype = "respray", price = 500, modid = 94},
                            {spraytype = "classic", name = "Maple Brown",      colortype = "primary", modtype = "respray", price = 500, modid = 97},
                            {spraytype = "classic", name = "Beechwood Brown",  colortype = "primary", modtype = "respray", price = 500, modid = 103},
                            {spraytype = "classic", name = "Sienna Brown",     colortype = "primary", modtype = "respray", price = 500, modid = 104},
                            {spraytype = "classic", name = "Saddle Brown",     colortype = "primary", modtype = "respray", price = 500, modid = 98},
                            {spraytype = "classic", name = "Moss Brown",       colortype = "primary", modtype = "respray", price = 500, modid = 100},
                            {spraytype = "classic", name = "Woodbeech Brown",  colortype = "primary", modtype = "respray", price = 500, modid = 102},
                            {spraytype = "classic", name = "Straw Brown",      colortype = "primary", modtype = "respray", price = 500, modid = 99},
                            {spraytype = "classic", name = "Sandy Brown",      colortype = "primary", modtype = "respray", price = 500, modid = 105},
                            {spraytype = "classic", name = "Bleached Brown",   colortype = "primary", modtype = "respray", price = 500, modid = 106},
                            {spraytype = "classic", name = "Schafter Purple",  colortype = "primary", modtype = "respray", price = 500, modid = 71},
                            {spraytype = "classic", name = "Spinnaker Purple", colortype = "primary", modtype = "respray", price = 500, modid = 72},
                            {spraytype = "classic", name = "Midnight Purple",  colortype = "primary", modtype = "respray", price = 500, modid = 142},
                            {spraytype = "classic", name = "Bright Purple",    colortype = "primary", modtype = "respray", price = 500, modid = 145},
                            {spraytype = "classic", name = "Cream",            colortype = "primary", modtype = "respray", price = 500, modid = 107},
                            {spraytype = "classic", name = "Ice White",        colortype = "primary", modtype = "respray", price = 500, modid = 111},
                            {spraytype = "classic", name = "Frost White",      colortype = "primary", modtype = "respray", price = 500, modid = 112}
                        }
                    },
                    {
                        id = "respray",
                        name = "Matte",    
                        buttons = { 
                            {spraytype = "matte", colortype = "primary", modtype = "respray", name = "Black" ,increaseby = 0, modid = 12,price = 500},
                            {spraytype = "matte", colortype = "primary", modtype = "respray", name = "Gray" ,increaseby = 0, modid = 13,price = 500},
                            {spraytype = "matte", colortype = "primary", modtype = "respray", name = "Light Gray" ,increaseby = 0, modid = 14,price = 500},
                            {spraytype = "matte", colortype = "primary", modtype = "respray", name = "Ice White" ,increaseby = 0, modid = 131,price = 500},
                            {spraytype = "matte", colortype = "primary", modtype = "respray", name = "Blue" ,increaseby = 0, modid = 83,price = 500},
                            {spraytype = "matte", colortype = "primary", modtype = "respray", name = "Dark Blue" ,increaseby = 0, modid = 82,price = 500},
                            {spraytype = "matte", colortype = "primary", modtype = "respray", name = "Midnight Blue" ,increaseby = 0, modid = 84,price = 500},
                            {spraytype = "matte", colortype = "primary", modtype = "respray", name = "Midnight Purple" ,increaseby = 0, modid = 149,price = 500},
                            {spraytype = "matte", colortype = "primary", modtype = "respray", name = "Schafter Purple" ,increaseby = 0, modid = 148,price = 500},
                            {spraytype = "matte", colortype = "primary", modtype = "respray", name = "Red" ,increaseby = 0, modid = 39,price = 500},
                            {spraytype = "matte", colortype = "primary", modtype = "respray", name = "Dark Red" ,increaseby = 0, modid = 40,price = 500},
                            {spraytype = "matte", colortype = "primary", modtype = "respray", name = "Orange" ,increaseby = 0, modid = 41,price = 500},
                            {spraytype = "matte", colortype = "primary", modtype = "respray", name = "Yellow" ,increaseby = 0, modid = 42,price = 500},
                            {spraytype = "matte", colortype = "primary", modtype = "respray", name = "Lime Green" ,increaseby = 0, modid = 55,price = 500},
                            {spraytype = "matte", colortype = "primary", modtype = "respray", name = "Green" ,increaseby = 0, modid = 128,price = 500},
                            {spraytype = "matte", colortype = "primary", modtype = "respray", name = "Frost Green" ,increaseby = 0, modid = 151,price = 500},
                            {spraytype = "matte", colortype = "primary", modtype = "respray", name = "Foliage Green" ,increaseby = 0, modid = 155,price = 500},
                            {spraytype = "matte", colortype = "primary", modtype = "respray", name = "Olive Darb" ,increaseby = 0, modid = 152,price = 500},
                            {spraytype = "matte", colortype = "primary", modtype = "respray", name = "Dark Earth" ,increaseby = 0, modid = 153,price = 500},
                            {spraytype = "matte", colortype = "primary", modtype = "respray", name = "Desert Tan" ,increaseby = 0, modid = 154,price = 500}
                        }
                    },
                    {
                        id = "respray",
                        name = "Metallic", 
                        buttons = { 
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Black",price = 500 ,increaseby = 0, modid = 0},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Carbon Black",price = 500 ,increaseby = 0, modid = 147},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Hraphite",price = 500 ,increaseby = 0, modid = 1},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Anhracite Black",price = 500 ,increaseby = 0, modid = 11},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Black Steel",price = 500 ,increaseby = 0, modid = 2},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Dark Steel",price = 500 ,increaseby = 0, modid = 3},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Silver",price = 500 ,increaseby = 0, modid = 4},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Bluish Silver",price = 500 ,increaseby = 0, modid = 5},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Rolled Steel",price = 500 ,increaseby = 0, modid = 6},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Shadow Silver",price = 500 ,increaseby = 0, modid = 7},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Stone Silver",price = 500 ,increaseby = 0, modid = 8},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Midnight Silver",price = 500 ,increaseby = 0, modid = 9},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Cast Iron Silver",price = 500 ,increaseby = 0, modid = 10},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Red",price = 500 ,increaseby = 0, modid = 27},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Torino Red",price = 500 ,increaseby = 0, modid = 28},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Formula Red",price = 500 ,increaseby = 0, modid = 29},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Lava Red",price = 500 ,increaseby = 0, modid = 150},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Blaze Red",price = 500 ,increaseby = 0, modid = 30},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Grace Red",price = 500 ,increaseby = 0, modid = 31},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Garnet Red",price = 500 ,increaseby = 0, modid = 32},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Sunset Red",price = 500 ,increaseby = 0, modid = 33},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Cabernet Red",price = 500 ,increaseby = 0, modid = 34},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Wine Red",price = 500 ,increaseby = 0, modid = 143},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Candy Red",price = 500 ,increaseby = 0, modid = 35},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Hot Pink",price = 500 ,increaseby = 0, modid = 135},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Pfsiter Pink",price = 500 ,increaseby = 0, modid = 137},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Salmon Pink",price = 500 ,increaseby = 0, modid = 136},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Sunrise Orange",price = 500 ,increaseby = 0, modid = 36},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Orange",price = 500 ,increaseby = 0, modid = 38},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Bright Orange",price = 500 ,increaseby = 0, modid = 138},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Gold",price = 500 ,increaseby = 0, modid = 99},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Bronze",price = 500 ,increaseby = 0, modid = 90},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Yellow",price = 500 ,increaseby = 0, modid = 88},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Race Yellow",price = 500 ,increaseby = 0, modid = 89},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Dew Yellow",price = 500 ,increaseby = 0, modid = 91},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Dark Green",price = 500 ,increaseby = 0, modid = 49},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Racing Green",price = 500 ,increaseby = 0, modid = 50},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Sea Green",price = 500 ,increaseby = 0, modid = 51},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Olive Green",price = 500 ,increaseby = 0, modid = 52},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Bright Green",price = 500 ,increaseby = 0, modid = 53},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Gasoline Green",price = 500 ,increaseby = 0, modid = 54},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Lime Green",price = 500 ,increaseby = 0, modid = 92},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Midnight Blue",price = 500 ,increaseby = 0, modid = 141},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Galaxy Blue",price = 500 ,increaseby = 0, modid = 61},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Dark Blue",price = 500 ,increaseby = 0, modid = 62},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Saxon Blue",price = 500 ,increaseby = 0, modid = 63},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Blue",price = 500 ,increaseby = 0, modid = 64},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Mariner Blue",price = 500 ,increaseby = 0, modid = 65},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Harbor Blue",price = 500 ,increaseby = 0, modid = 66},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Diamond Blue",price = 500 ,increaseby = 0, modid = 67},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Surf Blue",price = 500 ,increaseby = 0, modid = 68},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Nautical Blue",price = 500 ,increaseby = 0, modid = 69},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Racing Blue",price = 500 ,increaseby = 0, modid = 73},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Ultra Blue",price = 500 ,increaseby = 0, modid = 70},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Light Blue",price = 500 ,increaseby = 0, modid = 74},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Chocolate Brown",price = 500 ,increaseby = 0, modid = 96},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Bison Brown",price = 500 ,increaseby = 0, modid = 101},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Creeen Brown",price = 500 ,increaseby = 0, modid = 95},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Feltzer Brown",price = 500 ,increaseby = 0, modid = 94},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Maple Brown",price = 500 ,increaseby = 0, modid = 97},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Beechwood Brown",price = 500 ,increaseby = 0, modid = 103},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Sienna Brown",price = 500 ,increaseby = 0, modid = 104},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Saddle Brown",price = 500 ,increaseby = 0, modid = 98},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Moss Brown",price = 500 ,increaseby = 0, modid = 100},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Woodbeech Brown",price = 500 ,increaseby = 0, modid = 102},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Straw Brown",price = 500 ,increaseby = 0, modid = 99},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Sandy Brown",price = 500 ,increaseby = 0, modid = 105},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Bleached Brown",price = 500 ,increaseby = 0, modid = 106},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Schafter Purple",price = 500 ,increaseby = 0, modid = 71},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Spinnaker Purple",price = 500 ,increaseby = 0, modid = 72},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Midnight Purple",price = 500 ,increaseby = 0, modid = 142},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Bright Purple",price = 500 ,increaseby = 0, modid = 145},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Cream",price = 500 ,increaseby = 0, modid = 107},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Ice White",price = 500 ,increaseby = 0, modid = 111},
                            {spraytype = "metallic", colortype = "primary", modtype = "respray",name = "Frost White",price = 500 ,increaseby = 0, modid = 112}
                        }
                    },
                    {
                        id = "respray",
                        name = "Metals",   
                        buttons = { 
                            {spraytype = "metal", colortype = "primary", modtype = "respray", name = "Brushed Steel",modid = 117,price = 500},
                            {spraytype = "metal", colortype = "primary", modtype = "respray", name = "Brushed Black Steel",modid = 118,price = 500},
                            {spraytype = "metal", colortype = "primary", modtype = "respray", name = "Brushed Aluminum",modid = 119,price = 500},
                            {spraytype = "metal", colortype = "primary", modtype = "respray", name = "Pure Gold",modid = 158,price = 500},
                            {spraytype = "metal", colortype = "primary", modtype = "respray", name = "Brushed Gold",modid = 159,price = 500}
                        }
                    }
                },
            }, 
            [2] = {
                id = "respray",
                name = "Secondary Color", 
                buttons = {
                    {
                        id = "respray",
                        name = "Chrome",  
                        buttons = {
                            {spraytype = "chrome", colortype = "secondary", modtype = "respray", name = "Chrome", modid = 120, price = 1000,}
                        }
                    },
                    {
                        id = "respray",
                        name = "Classic",  
                        buttons = { 
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Black",price = 500 ,increaseby = 0, modid = 0},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Carbon Black",price = 500 ,increaseby = 0, modid = 147},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Hraphite",price = 500 ,increaseby = 0, modid = 1},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Anhracite Black",price = 500 ,increaseby = 0, modid = 11},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Black Steel",price = 500 ,increaseby = 0, modid = 2},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Dark Steel",price = 500 ,increaseby = 0, modid = 3},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Silver",price = 500 ,increaseby = 0, modid = 4},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Bluish Silver",price = 500 ,increaseby = 0, modid = 5},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Rolled Steel",price = 500 ,increaseby = 0, modid = 6},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Shadow Silver",price = 500 ,increaseby = 0, modid = 7},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Stone Silver",price = 500 ,increaseby = 0, modid = 8},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Midnight Silver",price = 500 ,increaseby = 0, modid = 9},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Cast Iron Silver",price = 500 ,increaseby = 0, modid = 10},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Red",price = 500 ,increaseby = 0, modid = 27},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Torino Red",price = 500 ,increaseby = 0, modid = 28},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Formula Red",price = 500 ,increaseby = 0, modid = 29},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Lava Red",price = 500 ,increaseby = 0, modid = 150},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Blaze Red",price = 500 ,increaseby = 0, modid = 30},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Grace Red",price = 500 ,increaseby = 0, modid = 31},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Garnet Red",price = 500 ,increaseby = 0, modid = 32},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Sunset Red",price = 500 ,increaseby = 0, modid = 33},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Cabernet Red",price = 500 ,increaseby = 0, modid = 34},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Wine Red",price = 500 ,increaseby = 0, modid = 143},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Candy Red",price = 500 ,increaseby = 0, modid = 35},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Hot Pink",price = 500 ,increaseby = 0, modid = 135},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Pfsiter Pink",price = 500 ,increaseby = 0, modid = 137},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Salmon Pink",price = 500 ,increaseby = 0, modid = 136},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Sunrise Orange",price = 500 ,increaseby = 0, modid = 36},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Orange",price = 500 ,increaseby = 0, modid = 38},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Bright Orange",price = 500 ,increaseby = 0, modid = 138},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Gold",price = 500 ,increaseby = 0, modid = 99},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Bronze",price = 500 ,increaseby = 0, modid = 90},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Yellow",price = 500 ,increaseby = 0, modid = 88},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Race Yellow",price = 500 ,increaseby = 0, modid = 89},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Dew Yellow",price = 500 ,increaseby = 0, modid = 91},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Dark Green",price = 500 ,increaseby = 0, modid = 49},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Racing Green",price = 500 ,increaseby = 0, modid = 50},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Sea Green",price = 500 ,increaseby = 0, modid = 51},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Olive Green",price = 500 ,increaseby = 0, modid = 52},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Bright Green",price = 500 ,increaseby = 0, modid = 53},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Gasoline Green",price = 500 ,increaseby = 0, modid = 54},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Lime Green",price = 500 ,increaseby = 0, modid = 92},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Midnight Blue",price = 500 ,increaseby = 0, modid = 141},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Galaxy Blue",price = 500 ,increaseby = 0, modid = 61},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Dark Blue",price = 500 ,increaseby = 0, modid = 62},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Saxon Blue",price = 500 ,increaseby = 0, modid = 63},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Blue",price = 500 ,increaseby = 0, modid = 64},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Mariner Blue",price = 500 ,increaseby = 0, modid = 65},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Harbor Blue",price = 500 ,increaseby = 0, modid = 66},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Diamond Blue",price = 500 ,increaseby = 0, modid = 67},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Surf Blue",price = 500 ,increaseby = 0, modid = 68},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Nautical Blue",price = 500 ,increaseby = 0, modid = 69},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Racing Blue",price = 500 ,increaseby = 0, modid = 73},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Ultra Blue",price = 500 ,increaseby = 0, modid = 70},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Light Blue",price = 500 ,increaseby = 0, modid = 74},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Chocolate Brown",price = 500 ,increaseby = 0, modid = 96},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Bison Brown",price = 500 ,increaseby = 0, modid = 101},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Creeen Brown",price = 500 ,increaseby = 0, modid = 95},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Feltzer Brown",price = 500 ,increaseby = 0, modid = 94},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Maple Brown",price = 500 ,increaseby = 0, modid = 97},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Beechwood Brown",price = 500 ,increaseby = 0, modid = 103},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Sienna Brown",price = 500 ,increaseby = 0, modid = 104},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Saddle Brown",price = 500 ,increaseby = 0, modid = 98},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Moss Brown",price = 500 ,increaseby = 0, modid = 100},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Woodbeech Brown",price = 500 ,increaseby = 0, modid = 102},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Straw Brown",price = 500 ,increaseby = 0, modid = 99},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Sandy Brown",price = 500 ,increaseby = 0, modid = 105},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Bleached Brown",price = 500 ,increaseby = 0, modid = 106},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Schafter Purple",price = 500 ,increaseby = 0, modid = 71},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Spinnaker Purple",price = 500 ,increaseby = 0, modid = 72},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Midnight Purple",price = 500 ,increaseby = 0, modid = 142},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Bright Purple",price = 500 ,increaseby = 0, modid = 145},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Cream",price = 500 ,increaseby = 0, modid = 107},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Ice White",price = 500 ,increaseby = 0, modid = 111},
                            {spraytype = "classic", colortype = "secondary", modtype = "respray", name = "Frost White",price = 500 ,increaseby = 0, modid = 112}
                        }
                    },
                    {
                        id = "respray",
                        name = "Matte",    
                        buttons = { 
                            {spraytype = "matte", colortype = "secondary", modtype = "respray", name = "Black" ,increaseby = 0, modid = 12,price = 500},
                            {spraytype = "matte", colortype = "secondary", modtype = "respray", name = "Gray" ,increaseby = 0, modid = 13,price = 500},
                            {spraytype = "matte", colortype = "secondary", modtype = "respray", name = "Light Gray" ,increaseby = 0, modid = 14,price = 500},
                            {spraytype = "matte", colortype = "secondary", modtype = "respray", name = "Ice White" ,increaseby = 0, modid = 131,price = 500},
                            {spraytype = "matte", colortype = "secondary", modtype = "respray", name = "Blue" ,increaseby = 0, modid = 83,price = 500},
                            {spraytype = "matte", colortype = "secondary", modtype = "respray", name = "Dark Blue" ,increaseby = 0, modid = 82,price = 500},
                            {spraytype = "matte", colortype = "secondary", modtype = "respray", name = "Midnight Blue" ,increaseby = 0, modid = 84,price = 500},
                            {spraytype = "matte", colortype = "secondary", modtype = "respray", name = "Midnight Purple" ,increaseby = 0, modid = 149,price = 500},
                            {spraytype = "matte", colortype = "secondary", modtype = "respray", name = "Schafter Purple" ,increaseby = 0, modid = 148,price = 500},
                            {spraytype = "matte", colortype = "secondary", modtype = "respray", name = "Red" ,increaseby = 0, modid = 39,price = 500},
                            {spraytype = "matte", colortype = "secondary", modtype = "respray", name = "Dark Red" ,increaseby = 0, modid = 40,price = 500},
                            {spraytype = "matte", colortype = "secondary", modtype = "respray", name = "Orange" ,increaseby = 0, modid = 41,price = 500},
                            {spraytype = "matte", colortype = "secondary", modtype = "respray", name = "Yellow" ,increaseby = 0, modid = 42,price = 500},
                            {spraytype = "matte", colortype = "secondary", modtype = "respray", name = "Lime Green" ,increaseby = 0, modid = 55,price = 500},
                            {spraytype = "matte", colortype = "secondary", modtype = "respray", name = "Green" ,increaseby = 0, modid = 128,price = 500},
                            {spraytype = "matte", colortype = "secondary", modtype = "respray", name = "Frost Green" ,increaseby = 0, modid = 151,price = 500},
                            {spraytype = "matte", colortype = "secondary", modtype = "respray", name = "Foliage Green" ,increaseby = 0, modid = 155,price = 500},
                            {spraytype = "matte", colortype = "secondary", modtype = "respray", name = "Olive Darb" ,increaseby = 0, modid = 152,price = 500},
                            {spraytype = "matte", colortype = "secondary", modtype = "respray", name = "Dark Earth" ,increaseby = 0, modid = 153,price = 500},
                            {spraytype = "matte", colortype = "secondary", modtype = "respray", name = "Desert Tan" ,increaseby = 0, modid = 154,price = 500}
                        }
                    },
                    {
                        id = "respray",
                        name = "Metallic", 
                        buttons = { 
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Black",price = 500 ,increaseby = 0, modid = 0},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Carbon Black",price = 500 ,increaseby = 0, modid = 147},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Hraphite",price = 500 ,increaseby = 0, modid = 1},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Anhracite Black",price = 500 ,increaseby = 0, modid = 11},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Black Steel",price = 500 ,increaseby = 0, modid = 2},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Dark Steel",price = 500 ,increaseby = 0, modid = 3},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Silver",price = 500 ,increaseby = 0, modid = 4},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Bluish Silver",price = 500 ,increaseby = 0, modid = 5},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Rolled Steel",price = 500 ,increaseby = 0, modid = 6},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Shadow Silver",price = 500 ,increaseby = 0, modid = 7},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Stone Silver",price = 500 ,increaseby = 0, modid = 8},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Midnight Silver",price = 500 ,increaseby = 0, modid = 9},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Cast Iron Silver",price = 500 ,increaseby = 0, modid = 10},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Red",price = 500 ,increaseby = 0, modid = 27},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Torino Red",price = 500 ,increaseby = 0, modid = 28},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Formula Red",price = 500 ,increaseby = 0, modid = 29},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Lava Red",price = 500 ,increaseby = 0, modid = 150},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Blaze Red",price = 500 ,increaseby = 0, modid = 30},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Grace Red",price = 500 ,increaseby = 0, modid = 31},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Garnet Red",price = 500 ,increaseby = 0, modid = 32},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Sunset Red",price = 500 ,increaseby = 0, modid = 33},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Cabernet Red",price = 500 ,increaseby = 0, modid = 34},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Wine Red",price = 500 ,increaseby = 0, modid = 143},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Candy Red",price = 500 ,increaseby = 0, modid = 35},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Hot Pink",price = 500 ,increaseby = 0, modid = 135},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Pfsiter Pink",price = 500 ,increaseby = 0, modid = 137},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Salmon Pink",price = 500 ,increaseby = 0, modid = 136},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Sunrise Orange",price = 500 ,increaseby = 0, modid = 36},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Orange",price = 500 ,increaseby = 0, modid = 38},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Bright Orange",price = 500 ,increaseby = 0, modid = 138},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Gold",price = 500 ,increaseby = 0, modid = 99},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Bronze",price = 500 ,increaseby = 0, modid = 90},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Yellow",price = 500 ,increaseby = 0, modid = 88},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Race Yellow",price = 500 ,increaseby = 0, modid = 89},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Dew Yellow",price = 500 ,increaseby = 0, modid = 91},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Dark Green",price = 500 ,increaseby = 0, modid = 49},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Racing Green",price = 500 ,increaseby = 0, modid = 50},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Sea Green",price = 500 ,increaseby = 0, modid = 51},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Olive Green",price = 500 ,increaseby = 0, modid = 52},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Bright Green",price = 500 ,increaseby = 0, modid = 53},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Gasoline Green",price = 500 ,increaseby = 0, modid = 54},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Lime Green",price = 500 ,increaseby = 0, modid = 92},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Midnight Blue",price = 500 ,increaseby = 0, modid = 141},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Galaxy Blue",price = 500 ,increaseby = 0, modid = 61},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Dark Blue",price = 500 ,increaseby = 0, modid = 62},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Saxon Blue",price = 500 ,increaseby = 0, modid = 63},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Blue",price = 500 ,increaseby = 0, modid = 64},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Mariner Blue",price = 500 ,increaseby = 0, modid = 65},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Harbor Blue",price = 500 ,increaseby = 0, modid = 66},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Diamond Blue",price = 500 ,increaseby = 0, modid = 67},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Surf Blue",price = 500 ,increaseby = 0, modid = 68},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Nautical Blue",price = 500 ,increaseby = 0, modid = 69},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Racing Blue",price = 500 ,increaseby = 0, modid = 73},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Ultra Blue",price = 500 ,increaseby = 0, modid = 70},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Light Blue",price = 500 ,increaseby = 0, modid = 74},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Chocolate Brown",price = 500 ,increaseby = 0, modid = 96},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Bison Brown",price = 500 ,increaseby = 0, modid = 101},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Creeen Brown",price = 500 ,increaseby = 0, modid = 95},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Feltzer Brown",price = 500 ,increaseby = 0, modid = 94},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Maple Brown",price = 500 ,increaseby = 0, modid = 97},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Beechwood Brown",price = 500 ,increaseby = 0, modid = 103},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Sienna Brown",price = 500 ,increaseby = 0, modid = 104},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Saddle Brown",price = 500 ,increaseby = 0, modid = 98},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Moss Brown",price = 500 ,increaseby = 0, modid = 100},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Woodbeech Brown",price = 500 ,increaseby = 0, modid = 102},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Straw Brown",price = 500 ,increaseby = 0, modid = 99},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Sandy Brown",price = 500 ,increaseby = 0, modid = 105},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Bleached Brown",price = 500 ,increaseby = 0, modid = 106},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Schafter Purple",price = 500 ,increaseby = 0, modid = 71},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Spinnaker Purple",price = 500 ,increaseby = 0, modid = 72},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Midnight Purple",price = 500 ,increaseby = 0, modid = 142},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Bright Purple",price = 500 ,increaseby = 0, modid = 145},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Cream",price = 500 ,increaseby = 0, modid = 107},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Ice White",price = 500 ,increaseby = 0, modid = 111},
                            {spraytype = "metallic", colortype = "secondary", modtype = "respray", name = "Frost White",price = 500 ,increaseby = 0, modid = 112}
                        }
                    },
                    {
                        id = "respray",
                        name = "Metals",   
                        buttons = { 
                            {spraytype = "metal", colortype = "secondary", modtype = "respray", name = "Brushed Steel",modid = 117,price = 500},
                            {spraytype = "metal", colortype = "secondary", modtype = "respray", name = "Brushed Black Steel",modid = 118,price = 500},
                            {spraytype = "metal", colortype = "secondary", modtype = "respray", name = "Brushed Aluminum",modid = 119,price = 500},
                            {spraytype = "metal", colortype = "secondary", modtype = "respray", name = "Pure Gold",modid = 158,price = 500},
                            {spraytype = "metal", colortype = "secondary", modtype = "respray", name = "Brushed Gold",modid = 159,price = 500}
                        }
                    }
                },
            }, 
            [3] = {
                id = "respray",
                name = "Pearlescent Color", 
                buttons = {
                    {
                        id = "respray",
                        name = "Chrome",  
                        buttons = {
                            {spraytype = "chrome", colortype = "pearlescent", modtype = "respray", name = "Chrome", modid = 120, price = 1000,}
                        }
                    },
                    {
                        id = "respray",
                        name = "Classic",  
                        buttons = { 
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Black",price = 500 ,increaseby = 0, modid = 0},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Carbon Black",price = 500 ,increaseby = 0, modid = 147},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Hraphite",price = 500 ,increaseby = 0, modid = 1},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Anhracite Black",price = 500 ,increaseby = 0, modid = 11},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Black Steel",price = 500 ,increaseby = 0, modid = 2},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Dark Steel",price = 500 ,increaseby = 0, modid = 3},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Silver",price = 500 ,increaseby = 0, modid = 4},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Bluish Silver",price = 500 ,increaseby = 0, modid = 5},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Rolled Steel",price = 500 ,increaseby = 0, modid = 6},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Shadow Silver",price = 500 ,increaseby = 0, modid = 7},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Stone Silver",price = 500 ,increaseby = 0, modid = 8},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Midnight Silver",price = 500 ,increaseby = 0, modid = 9},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Cast Iron Silver",price = 500 ,increaseby = 0, modid = 10},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Red",price = 500 ,increaseby = 0, modid = 27},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Torino Red",price = 500 ,increaseby = 0, modid = 28},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Formula Red",price = 500 ,increaseby = 0, modid = 29},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Lava Red",price = 500 ,increaseby = 0, modid = 150},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Blaze Red",price = 500 ,increaseby = 0, modid = 30},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Grace Red",price = 500 ,increaseby = 0, modid = 31},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Garnet Red",price = 500 ,increaseby = 0, modid = 32},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Sunset Red",price = 500 ,increaseby = 0, modid = 33},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Cabernet Red",price = 500 ,increaseby = 0, modid = 34},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Wine Red",price = 500 ,increaseby = 0, modid = 143},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Candy Red",price = 500 ,increaseby = 0, modid = 35},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Hot Pink",price = 500 ,increaseby = 0, modid = 135},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Pfsiter Pink",price = 500 ,increaseby = 0, modid = 137},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Salmon Pink",price = 500 ,increaseby = 0, modid = 136},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Sunrise Orange",price = 500 ,increaseby = 0, modid = 36},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Orange",price = 500 ,increaseby = 0, modid = 38},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Bright Orange",price = 500 ,increaseby = 0, modid = 138},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Gold",price = 500 ,increaseby = 0, modid = 99},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Bronze",price = 500 ,increaseby = 0, modid = 90},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Yellow",price = 500 ,increaseby = 0, modid = 88},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Race Yellow",price = 500 ,increaseby = 0, modid = 89},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Dew Yellow",price = 500 ,increaseby = 0, modid = 91},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Dark Green",price = 500 ,increaseby = 0, modid = 49},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Racing Green",price = 500 ,increaseby = 0, modid = 50},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Sea Green",price = 500 ,increaseby = 0, modid = 51},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Olive Green",price = 500 ,increaseby = 0, modid = 52},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Bright Green",price = 500 ,increaseby = 0, modid = 53},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Gasoline Green",price = 500 ,increaseby = 0, modid = 54},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Lime Green",price = 500 ,increaseby = 0, modid = 92},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Midnight Blue",price = 500 ,increaseby = 0, modid = 141},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Galaxy Blue",price = 500 ,increaseby = 0, modid = 61},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Dark Blue",price = 500 ,increaseby = 0, modid = 62},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Saxon Blue",price = 500 ,increaseby = 0, modid = 63},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Blue",price = 500 ,increaseby = 0, modid = 64},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Mariner Blue",price = 500 ,increaseby = 0, modid = 65},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Harbor Blue",price = 500 ,increaseby = 0, modid = 66},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Diamond Blue",price = 500 ,increaseby = 0, modid = 67},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Surf Blue",price = 500 ,increaseby = 0, modid = 68},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Nautical Blue",price = 500 ,increaseby = 0, modid = 69},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Racing Blue",price = 500 ,increaseby = 0, modid = 73},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Ultra Blue",price = 500 ,increaseby = 0, modid = 70},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Light Blue",price = 500 ,increaseby = 0, modid = 74},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Chocolate Brown",price = 500 ,increaseby = 0, modid = 96},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Bison Brown",price = 500 ,increaseby = 0, modid = 101},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Creeen Brown",price = 500 ,increaseby = 0, modid = 95},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Feltzer Brown",price = 500 ,increaseby = 0, modid = 94},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Maple Brown",price = 500 ,increaseby = 0, modid = 97},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Beechwood Brown",price = 500 ,increaseby = 0, modid = 103},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Sienna Brown",price = 500 ,increaseby = 0, modid = 104},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Saddle Brown",price = 500 ,increaseby = 0, modid = 98},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Moss Brown",price = 500 ,increaseby = 0, modid = 100},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Woodbeech Brown",price = 500 ,increaseby = 0, modid = 102},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Straw Brown",price = 500 ,increaseby = 0, modid = 99},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Sandy Brown",price = 500 ,increaseby = 0, modid = 105},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Bleached Brown",price = 500 ,increaseby = 0, modid = 106},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Schafter Purple",price = 500 ,increaseby = 0, modid = 71},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Spinnaker Purple",price = 500 ,increaseby = 0, modid = 72},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Midnight Purple",price = 500 ,increaseby = 0, modid = 142},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Bright Purple",price = 500 ,increaseby = 0, modid = 145},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Cream",price = 500 ,increaseby = 0, modid = 107},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Ice White",price = 500 ,increaseby = 0, modid = 111},
                            {spraytype = "classic", colortype = "pearlescent", modtype = "respray", name = "Frost White",price = 500 ,increaseby = 0, modid = 112}
                        }
                    },
                    {
                        id = "respray",
                        name = "Matte",    
                        buttons = { 
                            {spraytype = "matte", colortype = "pearlescent", modtype = "respray", name = "Black" ,increaseby = 0, modid = 12,price = 500},
                            {spraytype = "matte", colortype = "pearlescent", modtype = "respray", name = "Gray" ,increaseby = 0, modid = 13,price = 500},
                            {spraytype = "matte", colortype = "pearlescent", modtype = "respray", name = "Light Gray" ,increaseby = 0, modid = 14,price = 500},
                            {spraytype = "matte", colortype = "pearlescent", modtype = "respray", name = "Ice White" ,increaseby = 0, modid = 131,price = 500},
                            {spraytype = "matte", colortype = "pearlescent", modtype = "respray", name = "Blue" ,increaseby = 0, modid = 83,price = 500},
                            {spraytype = "matte", colortype = "pearlescent", modtype = "respray", name = "Dark Blue" ,increaseby = 0, modid = 82,price = 500},
                            {spraytype = "matte", colortype = "pearlescent", modtype = "respray", name = "Midnight Blue" ,increaseby = 0, modid = 84,price = 500},
                            {spraytype = "matte", colortype = "pearlescent", modtype = "respray", name = "Midnight Purple" ,increaseby = 0, modid = 149,price = 500},
                            {spraytype = "matte", colortype = "pearlescent", modtype = "respray", name = "Schafter Purple" ,increaseby = 0, modid = 148,price = 500},
                            {spraytype = "matte", colortype = "pearlescent", modtype = "respray", name = "Red" ,increaseby = 0, modid = 39,price = 500},
                            {spraytype = "matte", colortype = "pearlescent", modtype = "respray", name = "Dark Red" ,increaseby = 0, modid = 40,price = 500},
                            {spraytype = "matte", colortype = "pearlescent", modtype = "respray", name = "Orange" ,increaseby = 0, modid = 41,price = 500},
                            {spraytype = "matte", colortype = "pearlescent", modtype = "respray", name = "Yellow" ,increaseby = 0, modid = 42,price = 500},
                            {spraytype = "matte", colortype = "pearlescent", modtype = "respray", name = "Lime Green" ,increaseby = 0, modid = 55,price = 500},
                            {spraytype = "matte", colortype = "pearlescent", modtype = "respray", name = "Green" ,increaseby = 0, modid = 128,price = 500},
                            {spraytype = "matte", colortype = "pearlescent", modtype = "respray", name = "Frost Green" ,increaseby = 0, modid = 151,price = 500},
                            {spraytype = "matte", colortype = "pearlescent", modtype = "respray", name = "Foliage Green" ,increaseby = 0, modid = 155,price = 500},
                            {spraytype = "matte", colortype = "pearlescent", modtype = "respray", name = "Olive Darb" ,increaseby = 0, modid = 152,price = 500},
                            {spraytype = "matte", colortype = "pearlescent", modtype = "respray", name = "Dark Earth" ,increaseby = 0, modid = 153,price = 500},
                            {spraytype = "matte", colortype = "pearlescent", modtype = "respray", name = "Desert Tan" ,increaseby = 0, modid = 154,price = 500}
                        }
                    },
                    {
                        id = "respray",
                        name = "Metallic", 
                        buttons = { 
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Black",price = 500 ,increaseby = 0, modid = 0},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Carbon Black",price = 500 ,increaseby = 0, modid = 147},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Hraphite",price = 500 ,increaseby = 0, modid = 1},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Anhracite Black",price = 500 ,increaseby = 0, modid = 11},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Black Steel",price = 500 ,increaseby = 0, modid = 2},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Dark Steel",price = 500 ,increaseby = 0, modid = 3},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Silver",price = 500 ,increaseby = 0, modid = 4},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Bluish Silver",price = 500 ,increaseby = 0, modid = 5},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Rolled Steel",price = 500 ,increaseby = 0, modid = 6},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Shadow Silver",price = 500 ,increaseby = 0, modid = 7},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Stone Silver",price = 500 ,increaseby = 0, modid = 8},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Midnight Silver",price = 500 ,increaseby = 0, modid = 9},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Cast Iron Silver",price = 500 ,increaseby = 0, modid = 10},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Red",price = 500 ,increaseby = 0, modid = 27},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Torino Red",price = 500 ,increaseby = 0, modid = 28},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Formula Red",price = 500 ,increaseby = 0, modid = 29},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Lava Red",price = 500 ,increaseby = 0, modid = 150},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Blaze Red",price = 500 ,increaseby = 0, modid = 30},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Grace Red",price = 500 ,increaseby = 0, modid = 31},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Garnet Red",price = 500 ,increaseby = 0, modid = 32},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Sunset Red",price = 500 ,increaseby = 0, modid = 33},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Cabernet Red",price = 500 ,increaseby = 0, modid = 34},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Wine Red",price = 500 ,increaseby = 0, modid = 143},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Candy Red",price = 500 ,increaseby = 0, modid = 35},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Hot Pink",price = 500 ,increaseby = 0, modid = 135},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Pfsiter Pink",price = 500 ,increaseby = 0, modid = 137},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Salmon Pink",price = 500 ,increaseby = 0, modid = 136},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Sunrise Orange",price = 500 ,increaseby = 0, modid = 36},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Orange",price = 500 ,increaseby = 0, modid = 38},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Bright Orange",price = 500 ,increaseby = 0, modid = 138},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Gold",price = 500 ,increaseby = 0, modid = 99},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Bronze",price = 500 ,increaseby = 0, modid = 90},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Yellow",price = 500 ,increaseby = 0, modid = 88},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Race Yellow",price = 500 ,increaseby = 0, modid = 89},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Dew Yellow",price = 500 ,increaseby = 0, modid = 91},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Dark Green",price = 500 ,increaseby = 0, modid = 49},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Racing Green",price = 500 ,increaseby = 0, modid = 50},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Sea Green",price = 500 ,increaseby = 0, modid = 51},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Olive Green",price = 500 ,increaseby = 0, modid = 52},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Bright Green",price = 500 ,increaseby = 0, modid = 53},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Gasoline Green",price = 500 ,increaseby = 0, modid = 54},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Lime Green",price = 500 ,increaseby = 0, modid = 92},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Midnight Blue",price = 500 ,increaseby = 0, modid = 141},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Galaxy Blue",price = 500 ,increaseby = 0, modid = 61},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Dark Blue",price = 500 ,increaseby = 0, modid = 62},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Saxon Blue",price = 500 ,increaseby = 0, modid = 63},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Blue",price = 500 ,increaseby = 0, modid = 64},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Mariner Blue",price = 500 ,increaseby = 0, modid = 65},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Harbor Blue",price = 500 ,increaseby = 0, modid = 66},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Diamond Blue",price = 500 ,increaseby = 0, modid = 67},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Surf Blue",price = 500 ,increaseby = 0, modid = 68},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Nautical Blue",price = 500 ,increaseby = 0, modid = 69},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Racing Blue",price = 500 ,increaseby = 0, modid = 73},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Ultra Blue",price = 500 ,increaseby = 0, modid = 70},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Light Blue",price = 500 ,increaseby = 0, modid = 74},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Chocolate Brown",price = 500 ,increaseby = 0, modid = 96},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Bison Brown",price = 500 ,increaseby = 0, modid = 101},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Creeen Brown",price = 500 ,increaseby = 0, modid = 95},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Feltzer Brown",price = 500 ,increaseby = 0, modid = 94},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Maple Brown",price = 500 ,increaseby = 0, modid = 97},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Beechwood Brown",price = 500 ,increaseby = 0, modid = 103},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Sienna Brown",price = 500 ,increaseby = 0, modid = 104},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Saddle Brown",price = 500 ,increaseby = 0, modid = 98},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Moss Brown",price = 500 ,increaseby = 0, modid = 100},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Woodbeech Brown",price = 500 ,increaseby = 0, modid = 102},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Straw Brown",price = 500 ,increaseby = 0, modid = 99},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Sandy Brown",price = 500 ,increaseby = 0, modid = 105},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Bleached Brown",price = 500 ,increaseby = 0, modid = 106},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Schafter Purple",price = 500 ,increaseby = 0, modid = 71},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Spinnaker Purple",price = 500 ,increaseby = 0, modid = 72},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Midnight Purple",price = 500 ,increaseby = 0, modid = 142},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Bright Purple",price = 500 ,increaseby = 0, modid = 145},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Cream",price = 500 ,increaseby = 0, modid = 107},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Ice White",price = 500 ,increaseby = 0, modid = 111},
                            {spraytype = "metallic", colortype = "pearlescent", modtype = "respray", name = "Frost White",price = 500 ,increaseby = 0, modid = 112}
                        }
                    },
                    {
                        id = "respray",
                        name = "Metals",   
                        buttons = { 
                            {spraytype = "metal", colortype = "pearlescent", modtype = "respray", name = "Brushed Steel",modid = 117,price = 500},
                            {spraytype = "metal", colortype = "pearlescent", modtype = "respray", name = "Brushed Black Steel",modid = 118,price = 500},
                            {spraytype = "metal", colortype = "pearlescent", modtype = "respray", name = "Brushed Aluminum",modid = 119,price = 500},
                            {spraytype = "metal", colortype = "pearlescent", modtype = "respray", name = "Pure Gold",modid = 158,price = 500},
                            {spraytype = "metal", colortype = "pearlescent", modtype = "respray", name = "Brushed Gold",modid = 159,price = 500}
                        }
                    }
                },
            },
        }
    },
    ["liveries"] = {
        id = 48,
        price = 1000,
        increaseby = 0,
        label = "Liveries",
        modtype = "liveries",
    },
}

RLCustoms.WheelAccessories = {
    { name = "White Tire Smoke",  modid = 20, modtype = "wheelaccessories", tireid = 1, smokecolor = {254,254,254}, price = 500, increaseby = 0},
    { name = "Black Tire Smoke",  modid = 20, modtype = "wheelaccessories", tireid = 2, smokecolor = {1,1,1},       price = 500, increaseby = 0},
    { name = "BLue Tire Smoke",   modid = 20, modtype = "wheelaccessories", tireid = 3, smokecolor = {0,150,255},   price = 500, increaseby = 0},
    { name = "Yellow Tire Smoke", modid = 20, modtype = "wheelaccessories", tireid = 4, smokecolor = {255,255,50},  price = 500, increaseby = 0},
    { name = "Orange Tire Smoke", modid = 20, modtype = "wheelaccessories", tireid = 5, smokecolor = {255,153,51},  price = 500, increaseby = 0},
    { name = "Red Tire Smoke",    modid = 20, modtype = "wheelaccessories", tireid = 6, smokecolor = {255,10,10},   price = 500, increaseby = 0},
    { name = "Green Tire Smoke",  modid = 20, modtype = "wheelaccessories", tireid = 7, smokecolor = {10,255,10},   price = 500, increaseby = 0},
    { name = "Purple Tire Smoke", modid = 20, modtype = "wheelaccessories", tireid = 8, smokecolor = {153,10,153},  price = 500, increaseby = 0},
    { name = "Pink Tire Smoke",   modid = 20, modtype = "wheelaccessories", tireid = 9, smokecolor = {255,102,178}, price = 500, increaseby = 0},
    { name = "Gray Tire Smoke",   modid = 20, modtype = "wheelaccessories", tireid = 10, smokecolor = {128,128,128}, price = 500, increaseby = 0},
}

RLCustoms.WheelColors = {
	{name = "Black",             price = 500, increaseby = 0, modtype = "wheelcolor", modid = 0},
	{name = "Carbon Black",      price = 500, increaseby = 0, modtype = "wheelcolor", modid = 147},
	{name = "Hraphite",          price = 500, increaseby = 0, modtype = "wheelcolor", modid = 1},
	{name = "Anhracite Black",   price = 500, increaseby = 0, modtype = "wheelcolor", modid = 11},
	{name = "Black Steel",       price = 500, increaseby = 0, modtype = "wheelcolor", modid = 2},
	{name = "Dark Steel",        price = 500, increaseby = 0, modtype = "wheelcolor", modid = 3},
	{name = "Silver",            price = 500, increaseby = 0, modtype = "wheelcolor", modid = 4},
	{name = "Bluish Silver",     price = 500, increaseby = 0, modtype = "wheelcolor", modid = 5},
	{name = "Rolled Steel",      price = 500, increaseby = 0, modtype = "wheelcolor", modid = 6},
	{name = "Shadow Silver",     price = 500, increaseby = 0, modtype = "wheelcolor", modid = 7},
	{name = "Stone Silver",      price = 500, increaseby = 0, modtype = "wheelcolor", modid = 8},
	{name = "Midnight Silver",   price = 500, increaseby = 0, modtype = "wheelcolor", modid = 9},
	{name = "Cast Iron Silver",  price = 500, increaseby = 0, modtype = "wheelcolor", modid = 10},
	{name = "Red",               price = 500, increaseby = 0, modtype = "wheelcolor", modid = 27},
	{name = "Torino Red",        price = 500, increaseby = 0, modtype = "wheelcolor", modid = 28},
	{name = "Formula Red",       price = 500, increaseby = 0, modtype = "wheelcolor", modid = 29},
	{name = "Lava Red",          price = 500, increaseby = 0, modtype = "wheelcolor", modid = 150},
	{name = "Blaze Red",         price = 500, increaseby = 0, modtype = "wheelcolor", modid = 30},
	{name = "Grace Red",         price = 500, increaseby = 0, modtype = "wheelcolor", modid = 31},
	{name = "Garnet Red",        price = 500, increaseby = 0, modtype = "wheelcolor", modid = 32},
	{name = "Sunset Red",        price = 500, increaseby = 0, modtype = "wheelcolor", modid = 33},
	{name = "Cabernet Red",      price = 500, increaseby = 0, modtype = "wheelcolor", modid = 34},
	{name = "Wine Red",          price = 500, increaseby = 0, modtype = "wheelcolor", modid = 143},
	{name = "Candy Red",         price = 500, increaseby = 0, modtype = "wheelcolor", modid = 35},
	{name = "Hot Pink",          price = 500, increaseby = 0, modtype = "wheelcolor", modid = 135},
	{name = "Pfsiter Pink",      price = 500, increaseby = 0, modtype = "wheelcolor", modid = 137},
	{name = "Salmon Pink",       price = 500, increaseby = 0, modtype = "wheelcolor", modid = 136},
	{name = "Sunrise Orange",    price = 500, increaseby = 0, modtype = "wheelcolor", modid = 36},
	{name = "Orange",            price = 500, increaseby = 0, modtype = "wheelcolor", modid = 38},
	{name = "Bright Orange",     price = 500, increaseby = 0, modtype = "wheelcolor", modid = 138},
	{name = "Gold",              price = 500, increaseby = 0, modtype = "wheelcolor", modid = 99},
	{name = "Bronze",            price = 500, increaseby = 0, modtype = "wheelcolor", modid = 90},
	{name = "Yellow",            price = 500, increaseby = 0, modtype = "wheelcolor", modid = 88},
	{name = "Race Yellow",       price = 500, increaseby = 0, modtype = "wheelcolor", modid = 89},
	{name = "Dew Yellow",        price = 500, increaseby = 0, modtype = "wheelcolor", modid = 91},
	{name = "Dark Green",        price = 500, increaseby = 0, modtype = "wheelcolor", modid = 49},
	{name = "Racing Green",      price = 500, increaseby = 0, modtype = "wheelcolor", modid = 50},
	{name = "Sea Green",         price = 500, increaseby = 0, modtype = "wheelcolor", modid = 51},
	{name = "Olive Green",       price = 500, increaseby = 0, modtype = "wheelcolor", modid = 52},
	{name = "Bright Green",      price = 500, increaseby = 0, modtype = "wheelcolor", modid = 53},
	{name = "Gasoline Green",    price = 500, increaseby = 0, modtype = "wheelcolor", modid = 54},
	{name = "Lime Green",        price = 500, increaseby = 0, modtype = "wheelcolor", modid = 92},
	{name = "Midnight Blue",     price = 500, increaseby = 0, modtype = "wheelcolor", modid = 141},
	{name = "Galaxy Blue",       price = 500, increaseby = 0, modtype = "wheelcolor", modid = 61},
	{name = "Dark Blue",         price = 500, increaseby = 0, modtype = "wheelcolor", modid = 62},
	{name = "Saxon Blue",        price = 500, increaseby = 0, modtype = "wheelcolor", modid = 63},
	{name = "Blue",              price = 500, increaseby = 0, modtype = "wheelcolor", modid = 64},
	{name = "Mariner Blue",      price = 500, increaseby = 0, modtype = "wheelcolor", modid = 65},
	{name = "Harbor Blue",       price = 500, increaseby = 0, modtype = "wheelcolor", modid = 66},
	{name = "Diamond Blue",      price = 500, increaseby = 0, modtype = "wheelcolor", modid = 67},
	{name = "Surf Blue",         price = 500, increaseby = 0, modtype = "wheelcolor", modid = 68},
	{name = "Nautical Blue",     price = 500, increaseby = 0, modtype = "wheelcolor", modid = 69},
	{name = "Racing Blue",       price = 500, increaseby = 0, modtype = "wheelcolor", modid = 73},
	{name = "Ultra Blue",        price = 500, increaseby = 0, modtype = "wheelcolor", modid = 70},
	{name = "Light Blue",        price = 500, increaseby = 0, modtype = "wheelcolor", modid = 74},
	{name = "Chocolate Brown",   price = 500, increaseby = 0, modtype = "wheelcolor", modid = 96},
	{name = "Bison Brown",       price = 500, increaseby = 0, modtype = "wheelcolor", modid = 101},
	{name = "Creeen Brown",      price = 500, increaseby = 0, modtype = "wheelcolor", modid = 95},
	{name = "Feltzer Brown",     price = 500, increaseby = 0, modtype = "wheelcolor", modid = 94},
	{name = "Maple Brown",       price = 500, increaseby = 0, modtype = "wheelcolor", modid = 97},
	{name = "Beechwood Brown",   price = 500, increaseby = 0, modtype = "wheelcolor", modid = 103},
	{name = "Sienna Brown",      price = 500, increaseby = 0, modtype = "wheelcolor", modid = 104},
	{name = "Saddle Brown",      price = 500, increaseby = 0, modtype = "wheelcolor", modid = 98},
	{name = "Moss Brown",        price = 500, increaseby = 0, modtype = "wheelcolor", modid = 100},
	{name = "Woodbeech Brown",   price = 500, increaseby = 0, modtype = "wheelcolor", modid = 102},
	{name = "Straw Brown",       price = 500, increaseby = 0, modtype = "wheelcolor", modid = 99},
	{name = "Sandy Brown",       price = 500, increaseby = 0, modtype = "wheelcolor", modid = 105},
	{name = "Bleached Brown",    price = 500, increaseby = 0, modtype = "wheelcolor", modid = 106},
	{name = "Schafter Purple",   price = 500, increaseby = 0, modtype = "wheelcolor", modid = 71},
	{name = "Spinnaker Purple",  price = 500, increaseby = 0, modtype = "wheelcolor", modid = 72},
	{name = "Midnight Purple",   price = 500, increaseby = 0, modtype = "wheelcolor", modid = 142},
	{name = "Bright Purple",     price = 500, increaseby = 0, modtype = "wheelcolor", modid = 145},
	{name = "Cream",             price = 500, increaseby = 0, modtype = "wheelcolor", modid = 107},
	{name = "Ice White",         price = 500, increaseby = 0, modtype = "wheelcolor", modid = 111},
	{name = "Frost White",       price = 500, increaseby = 0, modtype = "wheelcolor", modid = 112},
}

RLCustoms.indexToName = {
    [0] = "modSpoilers",
    [1] = "modFrontBumper",
    [2] = "modRearBumper",
    [3] = "modSideSkirt",
    [4] = "modExhaust",
    [5] = "modFrame",
    [6] = "modGrille",
    [7] = "modHood",
    [8] = "modFender",
    [9] = "modRightFender",
    [10] = "modRoof",
    [11] = "modEngine",
    [12] = "modBrakes",
    [13] = "modTransmission",
    [14] = "modHorns",
    [15] = "modSuspension",
    [16] = "modArmor",
    [18] = "modTurbo",
    [20] = "modSmokeEnabled",
    [22] = "modXenon",
    [23] = "modFrontWheels",
    [24] = "modBackWheels",
    [25] = "modPlateHolder",
    [26] = "modVanityPlate",
    [27] = "modTrimA",
    [28] = "modOrnaments",
    [29] = "modDashboard",
    [30] = "modDial",
    [31] = "modDoorSpeaker",
    [32] = "modSeats",
    [33] = "modSteeringWheel",
    [34] = "modShifterLeavers",
    [35] = "modAPlate",
    [36] = "modSpeakers",
    [37] = "modTrunk",
    [38] = "modHydrolic",
    [39] = "modEngineBlock",
    [40] = "modAirFilter",
    [41] = "modStruts",
    [42] = "modArchCover",
    [43] = "modAerials",
    [44] = "modTrimB",
    [45] = "modTank",
    [46] = "modWindows",
}